// Generated by generate.py from schema.json. Do not edit.
use serde::{Deserialize, Serialize};
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum Contract {
    #[serde(rename = "metric-panel/1")]
    MetricPanel1,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum MetricId {
    #[serde(rename = "agent-records")]
    AgentRecords,
    #[serde(rename = "memory-used-ratio")]
    MemoryUsedRatio,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum Source {
    #[serde(rename = "smalltalk")]
    Smalltalk,
    #[serde(rename = "mimir")]
    Mimir,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum Unit {
    #[serde(rename = "count")]
    Count,
    #[serde(rename = "ratio")]
    Ratio,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum Freshness {
    #[serde(rename = "fresh")]
    Fresh,
    #[serde(rename = "stale")]
    Stale,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum Failure {
    #[serde(rename = "source-unavailable")]
    SourceUnavailable,
    #[serde(rename = "missing-series")]
    MissingSeries,
    #[serde(rename = "invalid-response")]
    InvalidResponse,
    #[serde(rename = "incomplete-source")]
    IncompleteSource,
}
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "state", deny_unknown_fields)]
pub enum Sample {
    #[serde(rename = "available")]
    Available {
        value: f64,
        observed_at: f64,
        age_seconds: f64,
        freshness: Freshness,
    },
    #[serde(rename = "unavailable")]
    Unavailable {
        reason: Failure,
        detail: String,
    },
}
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Panel {
    pub id: MetricId,
    pub title: String,
    pub subject: String,
    pub unit: Unit,
    pub source: Source,
    pub sample: Sample,
}
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PanelDocument {
    pub contract: Contract,
    pub generated_at: f64,
    pub panels: Vec<Panel>,
}
