"""Generate both language contracts from the same deliberately small JSON Schema dialect."""
import json
import pathlib
import re

root = pathlib.Path(__file__).parent
schema = json.loads((root / "schema.json").read_text())
definitions = schema["$defs"]

def variant(value):
    return "".join(word.title() for word in re.split(r"[^a-zA-Z0-9]+", value))

def rust_type(node):
    if "$ref" in node:
        return node["$ref"].rsplit("/", 1)[1]
    if node.get("type") == "array":
        return "Vec<" + rust_type(node["items"]) + ">"
    return {"string": "String", "number": "f64"}[node["type"]]

def ts_type(node):
    if "$ref" in node:
        return node["$ref"].rsplit("/", 1)[1]
    if "const" in node:
        return json.dumps(node["const"])
    if node.get("type") == "array":
        return "ReadonlyArray<" + ts_type(node["items"]) + ">"
    return {"string": "string", "number": "number"}[node["type"]]

rust = ["// Generated by generate.py from schema.json. Do not edit.", "use serde::{Deserialize, Serialize};"]
ts = ["// Generated by generate.py from schema.json. Do not edit."]
for name, node in definitions.items():
    if "enum" in node:
        rust += ["#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]", "pub enum " + name + " {"]
        for value in node["enum"]:
            rust += ["    #[serde(rename = " + json.dumps(value) + ")]", "    " + variant(value) + ","]
        rust += ["}"]
        ts += ["export type " + name + " = " + " | ".join(map(json.dumps, node["enum"])) + ";"]
    elif "oneOf" in node:
        rust += ["#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]", '#[serde(tag = "state", deny_unknown_fields)]', "pub enum " + name + " {"]
        alternatives = []
        for arm in node["oneOf"]:
            properties = arm["properties"]
            value = properties["state"]["const"]
            rust += ["    #[serde(rename = " + json.dumps(value) + ")]", "    " + variant(value) + " {"]
            for field, item in properties.items():
                if field != "state":
                    rust += ["        " + field + ": " + rust_type(item) + ","]
            rust += ["    },"]
            alternatives += ["{ " + "; ".join("readonly " + field + ": " + ts_type(item) for field, item in properties.items()) + " }"]
        rust += ["}"]
        ts += ["export type " + name + " = " + " | ".join(alternatives) + ";"]
    else:
        assert node["additionalProperties"] is False and set(node["required"]) == set(node["properties"])
        rust += ["#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]", "#[serde(deny_unknown_fields)]", "pub struct " + name + " {"]
        ts += ["export interface " + name + " {"]
        for field, item in node["properties"].items():
            rust += ["    pub " + field + ": " + rust_type(item) + ","]
            ts += ["    readonly " + field + ": " + ts_type(item) + ";"]
        rust += ["}"]
        ts += ["}"]
(root / "src" / "generated.rs").write_text("\n".join(rust) + "\n")
(root / "metric-panel.ts").write_text("\n".join(ts) + "\n")
