// Generated by generate.py from schema.json. Do not edit.
export type Contract = "metric-panel/1";
export type MetricId = "agent-records" | "memory-used-ratio";
export type Source = "smalltalk" | "mimir";
export type Unit = "count" | "ratio";
export type Freshness = "fresh" | "stale";
export type Failure = "source-unavailable" | "missing-series" | "invalid-response" | "incomplete-source";
export type Sample = { readonly state: "available"; readonly value: number; readonly observed_at: number; readonly age_seconds: number; readonly freshness: Freshness } | { readonly state: "unavailable"; readonly reason: Failure; readonly detail: string };
export interface Panel {
    readonly id: MetricId;
    readonly title: string;
    readonly subject: string;
    readonly unit: Unit;
    readonly source: Source;
    readonly sample: Sample;
}
export interface PanelDocument {
    readonly contract: Contract;
    readonly generated_at: number;
    readonly panels: ReadonlyArray<Panel>;
}
