// @generated by st3-client-codegen from schemas plus templates; do not edit this output.
import Foundation

public let st3ClientAPIVersion = "st3.client.v0"
public let st3ClientTerminalSubprotocol = "st3.client.terminal.v0"

public struct Envelope<Value: Codable & Sendable>: Codable, Sendable {
    public let apiVersion: String
    public let requestID: String
    public let snapshot: Snapshot
    public let value: Value
    enum CodingKeys: String, CodingKey { case apiVersion = "api_version", requestID = "request_id", snapshot, value }
}

public struct Snapshot: Codable, Sendable, Equatable {
    public let id: String
    public let hostID: String
    public let storeIndex: UInt64
    public let projectionVersion: String
    public let createdAt: String
    enum CodingKeys: String, CodingKey { case id, hostID = "host_id", storeIndex = "store_index", projectionVersion = "projection_version", createdAt = "created_at" }
}

public struct ErrorEnvelope: Codable, Error, Sendable {
    public let apiVersion: String
    public let errorVersion: String
    public let requestID: String
    public let code: ErrorCode
    public let message: String
    public let retryable: Bool
    public let retryAfterMS: UInt64?
    public let details: [String: JSONValue]
    enum CodingKeys: String, CodingKey { case apiVersion = "api_version", errorVersion = "error_version", requestID = "request_id", code, message, retryable, retryAfterMS = "retry_after_ms", details }
}

public enum ErrorCode: Codable, Sendable, Equatable {
    case notFound, forbidden, unsupportedCapability, validationFailed, idempotencyConflict
    case attentionMigrated
    case staleFence, cursorGap, pageCursorExpired, rateLimited
    case runtimeNotLocal, runtimeAuthorityIndeterminate, remoteUnavailable, `internal`
    case unknown(String)

    public init(from decoder: Decoder) throws {
        let raw = try decoder.singleValueContainer().decode(String.self)
        self = switch raw {
        case "attention-migrated": .attentionMigrated; case "not-found": .notFound; case "forbidden": .forbidden
        case "unsupported-capability": .unsupportedCapability; case "validation-failed": .validationFailed
        case "idempotency-conflict": .idempotencyConflict; case "stale-fence": .staleFence
        case "cursor-gap": .cursorGap; case "page-cursor-expired": .pageCursorExpired
        case "rate-limited": .rateLimited; case "runtime-not-local": .runtimeNotLocal
        case "runtime-authority-indeterminate": .runtimeAuthorityIndeterminate; case "remote-unavailable": .remoteUnavailable; case "internal": .internal
        default: .unknown(raw)
        }
    }
    public func encode(to encoder: Encoder) throws {
        let raw = switch self {
        case .attentionMigrated: "attention-migrated"; case .notFound: "not-found"; case .forbidden: "forbidden"
        case .unsupportedCapability: "unsupported-capability"; case .validationFailed: "validation-failed"
        case .idempotencyConflict: "idempotency-conflict"; case .staleFence: "stale-fence"
        case .cursorGap: "cursor-gap"; case .pageCursorExpired: "page-cursor-expired"
        case .rateLimited: "rate-limited"; case .runtimeNotLocal: "runtime-not-local"
        case .runtimeAuthorityIndeterminate: "runtime-authority-indeterminate"; case .remoteUnavailable: "remote-unavailable"; case .internal: "internal"
        case .unknown(let value): value
        }
        var container = encoder.singleValueContainer(); try container.encode(raw)
    }
}

public enum JSONValue: Codable, Sendable, Equatable {
    case null, bool(Bool), number(Double), string(String), array([JSONValue]), object([String: JSONValue])
    public init(from decoder: Decoder) throws {
        let box = try decoder.singleValueContainer()
        if box.decodeNil() { self = .null }
        else if let value = try? box.decode(Bool.self) { self = .bool(value) }
        else if let value = try? box.decode(Double.self) { self = .number(value) }
        else if let value = try? box.decode(String.self) { self = .string(value) }
        else if let value = try? box.decode([JSONValue].self) { self = .array(value) }
        else { self = .object(try box.decode([String: JSONValue].self)) }
    }
    public func encode(to encoder: Encoder) throws {
        var box = encoder.singleValueContainer()
        switch self { case .null: try box.encodeNil(); case .bool(let v): try box.encode(v); case .number(let v): try box.encode(v); case .string(let v): try box.encode(v); case .array(let v): try box.encode(v); case .object(let v): try box.encode(v) }
    }
}

public struct Capability: Codable, Sendable { public let id: String; public let version: UInt; public let state: String }
public struct Limits: Codable, Sendable {
    public let maxPageItems: Int; public let maxEventItems: Int; public let maxResponseBytes: Int; public let maxWaitMS: UInt64
    public let maxGlassBodyBytes, maxGlasses, maxGlassDepth, maxGlassNodes: Int?
    enum CodingKeys: String, CodingKey { case maxGlassBodyBytes = "max_glass_body_bytes", maxGlasses = "max_glasses", maxGlassDepth = "max_glass_depth", maxGlassNodes = "max_glass_nodes", maxPageItems = "max_page_items", maxEventItems = "max_event_items", maxResponseBytes = "max_response_bytes", maxWaitMS = "max_wait_ms" }
}
public struct Capabilities: Codable, Sendable {
    public let kind: String; public let sessionActor: String; public let transport: String; public let capabilities: [Capability]; public let limits: Limits; public let eventCursor: String; public let oldestEventCursor: String; public let schemas: [String]
    enum CodingKeys: String, CodingKey { case kind, sessionActor = "session_actor", transport, capabilities, limits, eventCursor = "event_cursor", oldestEventCursor = "oldest_event_cursor", schemas }
}

public struct PageInfo: Codable, Sendable { public let limit: Int; public let hasMore: Bool; public let nextCursor: String?; public let cursorExpiresAt: String?; enum CodingKeys: String, CodingKey { case limit, hasMore = "has_more", nextCursor = "next_cursor", cursorExpiresAt = "cursor_expires_at" } }
public struct Operational: Codable, Sendable { public let layer: String; public let actionable: Bool; public let reasons: [String]?; public let ownerGeneration: String?; public let runtimeIncarnation: String?; enum CodingKeys: String, CodingKey { case layer, actionable, reasons, ownerGeneration = "owner_generation", runtimeIncarnation = "runtime_incarnation" } }
public struct StructuredDiff: Codable, Sendable { public let changes: [JSONValue]; public let predictedActions: [JSONValue]; enum CodingKeys: String, CodingKey { case changes, predictedActions = "predicted_actions" } }
public struct VisualizationNode: Codable, Sendable { public let id, kind, label, path: String; public let goals, constraints: [String]; public let assignment: JSONValue?; public let timeoutMS: UInt64?; public let retry: JSONValue; public let gates: [JSONValue]; public let loopSpec: JSONValue?; public let resources, sourceReferences: [JSONValue]; public let runtime: JSONValue; enum CodingKeys: String, CodingKey { case id, kind, label, path, goals, constraints, assignment, timeoutMS = "timeout_ms", retry, gates, loopSpec = "loop", resources, sourceReferences = "source_references", runtime } }
public struct VisualizationEdge: Codable, Sendable { public let id, kind: String; public let from: String?; public let to: String; public let gate: JSONValue }
public struct VisualizationGroup: Codable, Sendable { public let id, kind: String; public let members: [String] }
public struct VisualizationTimeline: Codable, Sendable { public let entries: [JSONValue] }
public struct VisualizationSwimlane: Codable, Sendable { public let id, assignment: String; public let nodes: [String] }
public struct Visualization: Codable, Sendable {
    public let version: String; public let views: [String]; public let mission: String?
    public let nodes: [VisualizationNode]; public let edges: [VisualizationEdge]; public let groups: [VisualizationGroup]
    public let timeline: VisualizationTimeline; public let swimlanes: [VisualizationSwimlane]
    public let goals: [String]; public let constraints: [String]; public let gates: [JSONValue]
    public let resources: [JSONValue]; public let decisions: [LaunchDecisionResource]; public let revision: JSONValue; public let diffs: [StructuredDiff]; public let risk: JSONValue; public let liveProgress: JSONValue
    enum CodingKeys: String, CodingKey { case version, views, mission, nodes, edges, groups, timeline, swimlanes, goals, constraints, gates, resources, decisions, revision, diffs, risk, liveProgress = "live_progress" }
}
public struct UsageContext: Codable, Sendable {
    public let usedTokens: UInt64?; public let windowTokens: UInt64?; public let usedPercent: Double?; public let model: String?; public let compactions: UInt64?; public let lastCompactionMs: UInt64?; public let lastCompactionTrigger: String?; public let observedAtUnixMS: UInt64
    enum CodingKeys: String, CodingKey { case usedTokens = "used_tokens", windowTokens = "window_tokens", usedPercent = "used_percent", model, compactions, lastCompactionMs = "last_compaction_ms", lastCompactionTrigger = "last_compaction_trigger", observedAtUnixMS = "observed_at_unix_ms" }
}
public struct UsageSummary: Codable, Sendable {
    public let totalTokens: UInt64; public let inputTokens: UInt64; public let outputTokens: UInt64; public let cachedTokens: UInt64
    public let cost: Double?; public let currency: String?; public let incarnationCount: Int; public let aggregation: String; public let context: UsageContext?
    enum CodingKeys: String, CodingKey { case totalTokens = "total_tokens", inputTokens = "input_tokens", outputTokens = "output_tokens", cachedTokens = "cached_tokens", cost, currency, incarnationCount = "incarnation_count", aggregation, context }
}
public struct AttentionResource: Codable, Sendable { public let id, kind, revision, updatedAt, attentionKind, sourceID, personID, title, detail, priority, state, requestedAt: String; public let requesterID, launchID, variantID, messageID, previewToken, what, because, reviewMode, missionID, missionRunID, stepRunID, episode, sourceKind: String?; public let actionParameters: JSONValue?; public let preview: LaunchPreview?; public let fix: JSONValue?; public let targets, actions: [String]; public let targetStates: [AttentionTargetState]?; public let operational: Operational?; enum CodingKeys: String, CodingKey { case id, kind, revision, updatedAt = "updated_at", attentionKind = "attention_kind", episode, sourceKind = "source_kind", actionParameters = "action_parameters", sourceID = "source_id", personID = "person_id", requesterID = "requester_id", launchID = "launch_id", variantID = "variant_id", messageID = "message_id", previewToken = "preview_token", preview, what, because, fix, reviewMode = "review_mode", missionID = "mission_id", missionRunID = "mission_run_id", stepRunID = "step_run_id", title, detail, priority, state, requestedAt = "requested_at", targets, targetStates = "target_states", actions, operational } }
public struct AttentionTargetState: Codable, Sendable { public let id, state: String; public let since: String? }
public struct DocumentContent: Codable, Sendable { public let reference: String; public let bytes: [UInt8] }
public struct AgentDeclaration: Codable, Sendable { public let id, revision, kdl: String; public let tree: [String: JSONValue]; public let revisions: [String] }
public struct CanonicalNode: Codable, Sendable { public let name: String; public let arguments: [JSONValue]?; public let properties: [String: JSONValue]?; public let children: [CanonicalNode]? }
public struct SubjectDefinition: Codable, Sendable { public let kind, subject, kdl, desiredRevision, desiredToken: String; public let desired: CanonicalNode; public let conflicts: [String]; enum CodingKeys: String, CodingKey { case kind, subject, desired, kdl, desiredRevision = "desired_revision", desiredToken = "desired_token", conflicts } }
public struct LaunchPreview: Codable, Sendable { public let goal: String; public let steps, agents: [JSONValue]; public let gates: JSONValue; public let diagnosticsCount: UInt64; public let requestExcerpt: String; enum CodingKeys: String, CodingKey { case goal, steps, agents, gates, diagnosticsCount = "diagnostics_count", requestExcerpt = "request_excerpt" } }
public struct MessageResource: Codable, Sendable { public let id, kind, revision, updatedAt, from, to, content, state, sentAt: String; public let title, inReplyTo, sessionID: String?; public let tags: [String]; public let operational: Operational?; enum CodingKeys: String, CodingKey { case id, kind, revision, updatedAt = "updated_at", from, to, title, content, state, sentAt = "sent_at", inReplyTo = "in_reply_to", sessionID = "session_id", tags, operational } }
public enum PlannerProvider: String, Codable, Sendable { case codex, claude, pi, omp, opencode }
public struct PlannerConfig: Codable, Sendable { public let provider: PlannerProvider; public let model, effort: String? }
public struct LaunchResource: Codable, Sendable { public let id, kind, revision, updatedAt, title, phase, request, planner: String; public let plannerConfig: PlannerConfig; public let target: JSONValue; public let variants, decisions, approvals: [String]; public let visualization: Visualization?; public let previewToken: String?; public let preview: LaunchPreview?; public let operational: Operational?; enum CodingKeys: String, CodingKey { case id, kind, revision, updatedAt = "updated_at", title, phase, request, previewToken = "preview_token", preview, planner, plannerConfig = "planner_config", target, variants, decisions, approvals, visualization, operational } }
public struct LaunchVariantResource: Codable, Sendable { public let id, kind, revision, updatedAt, launchID, status: String; public let ordinal, candidateRevision: UInt64; public let targetGeneration: String?; public let normalizedMission: JSONValue; public let diagnostics: [JSONValue]; public let previewToken: String?; public let structuredDiff: StructuredDiff?; public let visualization: Visualization?; public let operational: Operational?; enum CodingKeys: String, CodingKey { case id, kind, revision, updatedAt = "updated_at", launchID = "launch_id", ordinal, candidateRevision = "candidate_revision", status, targetGeneration = "target_generation", normalizedMission = "normalized_mission", diagnostics, previewToken = "preview_token", structuredDiff = "structured_diff", visualization, operational } }
public enum DecisionType: String, Codable, Sendable { case boolean, singleChoice = "single-choice", multipleChoice = "multiple-choice", rank }
public struct DecisionOption: Codable, Sendable, Equatable { public let id: String; public let label: String; public let description: String? }
public enum DecisionResponse: Codable, Sendable, Equatable {
    case boolean(Bool), singleChoice(String), multipleChoice([String]), rank([String])
    private enum CodingKeys: String, CodingKey { case type, value }
    private enum Kind: String, Codable { case boolean, singleChoice = "single-choice", multipleChoice = "multiple-choice", rank }
    public init(from decoder: Decoder) throws { let values = try decoder.container(keyedBy: CodingKeys.self); switch try values.decode(Kind.self, forKey: .type) { case .boolean: self = .boolean(try values.decode(Bool.self, forKey: .value)); case .singleChoice: self = .singleChoice(try values.decode(String.self, forKey: .value)); case .multipleChoice: self = .multipleChoice(try values.decode([String].self, forKey: .value)); case .rank: self = .rank(try values.decode([String].self, forKey: .value)) } }
    public func encode(to encoder: Encoder) throws { var values = encoder.container(keyedBy: CodingKeys.self); switch self { case .boolean(let value): try values.encode(Kind.boolean, forKey: .type); try values.encode(value, forKey: .value); case .singleChoice(let value): try values.encode(Kind.singleChoice, forKey: .type); try values.encode(value, forKey: .value); case .multipleChoice(let value): try values.encode(Kind.multipleChoice, forKey: .type); try values.encode(value, forKey: .value); case .rank(let value): try values.encode(Kind.rank, forKey: .type); try values.encode(value, forKey: .value) } }
}
public struct LaunchDecisionResource: Codable, Sendable { public let id, kind, revision, updatedAt, launchID, question, state, requestedAt: String; public let decisionType: DecisionType; public let options: [DecisionOption]; public let response: DecisionResponse?; public let explanation: String?; public let operational: Operational?; enum CodingKeys: String, CodingKey { case id, kind, revision, updatedAt = "updated_at", launchID = "launch_id", question, state, requestedAt = "requested_at", decisionType = "decision_type", options, response, explanation, operational } }
public struct LaunchApprovalResource: Codable, Sendable { public let id, kind, revision, updatedAt, launchID, variantID, reviewer, state, previewToken, decidedAt: String; public let operational: Operational?; enum CodingKeys: String, CodingKey { case id, kind, revision, updatedAt = "updated_at", launchID = "launch_id", variantID = "variant_id", reviewer, state, previewToken = "preview_token", decidedAt = "decided_at", operational } }
public struct MissionResource: Codable, Sendable { public let id, kind, revision, updatedAt, title, state, missionRevision: String; public let runs: [String]; public let runDetails: [MissionRunSummary]?; public let mustAct: String?; public let activeRuns: UInt64?; public let runGenerations: [String: String]; public let visualization: Visualization?; public let usage: UsageSummary?; public let operational: Operational?; enum CodingKeys: String, CodingKey { case id, kind, revision, updatedAt = "updated_at", title, state, missionRevision = "mission_revision", runs, runDetails = "run_details", mustAct = "must_act", activeRuns = "active_runs", runGenerations = "run_generations", visualization, usage, operational } }
public struct MissionRunSummary: Codable, Sendable { public let id, requester, status, phase, mustAct, stateSince: String; public let generationID, lastProgress, after, deadline: String?; public let progress: JSONValue; public let currentSteps: [JSONValue]; public let blocker: JSONValue?; public let outcome: MissionRunOutcome?; public let steps: [MissionStep]?; enum CodingKeys: String, CodingKey { case id, generationID = "generation_id", requester, status, phase, progress, currentSteps = "current_steps", mustAct = "must_act", stateSince = "state_since", outcome, lastProgress = "last_progress", blocker, after, deadline, steps } }
public struct MissionRunOutcome: Codable, Sendable { public let status, reason, actor, at: String; public let previousStatus: String?; enum CodingKeys: String, CodingKey { case status, previousStatus = "previous_status", reason, actor, at } }
public struct MissionStep: Codable, Sendable { public let id, path, state, since: String; public let title, assignee, claimant, lastProgress, blockedReason: String?; public let attempt: UInt; public let agentless: Bool?; public let blockers, goals, constraints: [String]?; enum CodingKeys: String, CodingKey { case id, path, title, state, attempt, assignee, claimant, agentless, since, lastProgress = "last_progress", blockedReason = "blocked_reason", blockers, goals, constraints } }
public struct WorkLabel: Codable, Sendable { public let id, missionID, missionRunID, path, state, since: String; public let title, goal: String?; enum CodingKeys: String, CodingKey { case id, missionID = "mission_id", missionRunID = "mission_run_id", path, title, goal, state, since } }
public struct WorkResource: Codable, Sendable { public let missionID: String?; public let id, kind, revision, updatedAt, missionRunID, generationID, definitionID, path, state: String; public let gateKind, title, assignedTo, lastProgress: String?; public let attempt: UInt; public let readinessEpoch: UInt64; public let claimant, claimIncarnation, blockedReason: String?; public let blockers, goals, constraints: [String]; public let usage: UsageSummary?; public let operational: Operational?; enum CodingKeys: String, CodingKey { case id, kind, revision, updatedAt = "updated_at", missionID = "mission_id", missionRunID = "mission_run_id", generationID = "generation_id", definitionID = "definition_id", path, state, gateKind = "gate_kind", title, assignedTo = "assigned_to", lastProgress = "last_progress", attempt, readinessEpoch = "readiness_epoch", claimant, claimIncarnation = "claim_incarnation", blockedReason = "blocked_reason", blockers, goals, constraints, usage, operational } }
public struct AgentRelationship: Codable, Sendable { public let agentID: String; public let reason: String?; enum CodingKeys: String, CodingKey { case agentID = "agent_id", reason } }
public struct AgentResource: Codable, Sendable { public let id, kind, revision, updatedAt, name, state, reachability: String; public let runtimeIDs: [String]; public let ownerRunID, driver, harnessState, hostID, lastActivityAt, silentSince, fault, incarnationID, currentSessionID: String?; public let currentWorkIDs, upcomingWorkIDs: [String]?; public let activeWorkCount, queuedWorkCount: UInt64?; public let nextWorkID: String?; public let currentWork, upcomingWork: [WorkLabel]?; public let nextWork: WorkLabel?; public let usage: UsageSummary?; public let under: [AgentRelationship]; public let delivery: AgentDelivery?; public let operational: Operational?; enum CodingKeys: String, CodingKey { case id, kind, revision, updatedAt = "updated_at", name, state, reachability, runtimeIDs = "runtime_ids", ownerRunID = "owner_run_id", driver, harnessState = "harness_state", hostID = "host_id", lastActivityAt = "last_activity_at", silentSince = "silent_since", fault, incarnationID = "incarnation_id", currentSessionID = "current_session_id", currentWorkIDs = "current_work_ids", activeWorkCount = "active_work_count", nextWorkID = "next_work_id", upcomingWorkIDs = "upcoming_work_ids", queuedWorkCount = "queued_work_count", currentWork = "current_work", nextWork = "next_work", upcomingWork = "upcoming_work", usage, under, delivery, operational } }
public struct AgentDelivery: Codable, Sendable { public let state: String; public let reason: String?; public let polledSecondsAgo: UInt64?; public let transport: String?; enum CodingKeys: String, CodingKey { case state, reason, polledSecondsAgo = "polled_seconds_ago", transport } }
public enum AgentQueuePlacement: String, Codable, Sendable { case top, bottom, before, after }
public struct AgentQueue: Codable, Sendable { public let kind: String; public let agentID: String; public let currentWorkIDs: [String]; public let nextWorkID: String?; public let runs: [AgentQueueRun]; public let moves: [AgentQueueMove]; public let moveCount: UInt64; enum CodingKeys: String, CodingKey { case kind, agentID = "agent_id", currentWorkIDs = "current_work_ids", nextWorkID = "next_work_id", runs, moves, moveCount = "move_count" } }
public struct AgentQueueRun: Codable, Sendable { public let missionRunID: String; public let position: UInt32; public let state: String; public let runState: String; public let joinedAt: String; public let claimedWorkIDs: [String]; public let readyWorkIDs: [String]; public let waitingWorkIDs: [String]; public let waitingForRunID: String?; enum CodingKeys: String, CodingKey { case missionRunID = "mission_run_id", position, state, runState = "run_state", joinedAt = "joined_at", claimedWorkIDs = "claimed_work_ids", readyWorkIDs = "ready_work_ids", waitingWorkIDs = "waiting_work_ids", waitingForRunID = "waiting_for_run_id" } }
public struct AgentQueueMove: Codable, Sendable { public let claimID: String; public let missionRunID: String; public let placement: AgentQueuePlacement; public let anchorRunID: String?; public let actorID: String?; public let reason: String?; public let movedAt: String; enum CodingKeys: String, CodingKey { case claimID = "claim_id", missionRunID = "mission_run_id", placement, anchorRunID = "anchor_run_id", actorID = "actor_id", reason, movedAt = "moved_at" } }
public struct TerminalAccess: Codable, Sendable { public let read, input, resize: String }
public struct RuntimeResource: Codable, Sendable { public let id, kind, revision, updatedAt, runtimeKind, ownerID, ownerHostID, state, runtimeID: String; public let desiredRevision, incarnationID, ownerRunID, terminalID: String?; public let terminalSequence: UInt64?; public let terminalAccess: TerminalAccess?; public let operational: Operational?; enum CodingKeys: String, CodingKey { case id, kind, revision, updatedAt = "updated_at", runtimeKind = "runtime_kind", ownerID = "owner_id", ownerHostID = "owner_host_id", state, runtimeID = "runtime_id", incarnationID = "incarnation_id", desiredRevision = "desired_revision", ownerRunID = "owner_run_id", terminalID = "terminal_id", terminalSequence = "terminal_sequence", terminalAccess = "terminal_access", operational } }
public struct ObserverSpec: Codable, Sendable { public let resource, provider, locator: String; public let fields: [String]; public let stopped: Bool }
public struct SubscriptionSpec: Codable, Sendable { public let observer, to, delivery: String; public let fields: [String]; public let condition: JSONValue?; public let mission, revision, resourceInput, workspace, requester: String?; public let stopped: Bool; enum CodingKeys: String, CodingKey { case observer, to, fields, condition, delivery, mission, revision, resourceInput = "resource_input", workspace, requester, stopped } }
public struct LaneResource: Codable, Sendable { public let id, kind, revision, updatedAt, name, state: String; public let missionRunID, missionID, entriesPrefix, approverID: String?; public let entries: [LaneEntry]; public let recent: [LaneChange]; public let operational: Operational?; enum CodingKeys: String, CodingKey { case id, kind, revision, updatedAt = "updated_at", name, state, missionRunID = "mission_run_id", missionID = "mission_id", entriesPrefix = "entries_prefix", approverID = "approver_id", entries, recent, operational } }
public struct LaneEntry: Codable, Sendable { public let entryID, label, state, joinedByID, joinedAt: String; public let position: UInt32; public let detail, head, markedByID, markedAt, joinReason, approvedByID, approvedAt: String?; enum CodingKeys: String, CodingKey { case entryID = "entry_id", label, position, state, detail, head, markedByID = "marked_by_id", markedAt = "marked_at", joinedByID = "joined_by_id", joinedAt = "joined_at", joinReason = "join_reason", approvedByID = "approved_by_id", approvedAt = "approved_at" } }
public struct LaneChange: Codable, Sendable { public let change, entryID, label, actorID, at: String; public let outcome: String?; public let placement: AgentQueuePlacement?; public let anchorID, reason: String?; enum CodingKeys: String, CodingKey { case change, entryID = "entry_id", label, actorID = "actor_id", at, outcome, placement, anchorID = "anchor_id", reason } }
public struct ObserverResource: Codable, Sendable { public let id, kind, revision, updatedAt, state: String; public let spec: ObserverSpec; public let ownerRunID, ownerGenerationID, ownerStepID: String?; public let operational: Operational?; enum CodingKeys: String, CodingKey { case id, kind, revision, updatedAt = "updated_at", state, spec, ownerRunID = "owner_run_id", ownerGenerationID = "owner_generation_id", ownerStepID = "owner_step_id", operational } }
public struct SubscriptionResource: Codable, Sendable { public let id, kind, revision, updatedAt, state: String; public let spec: SubscriptionSpec; public let ownerRunID, ownerGenerationID, ownerStepID: String?; public let operational: Operational?; enum CodingKeys: String, CodingKey { case id, kind, revision, updatedAt = "updated_at", state, spec, ownerRunID = "owner_run_id", ownerGenerationID = "owner_generation_id", ownerStepID = "owner_step_id", operational } }
public struct MachineCapacity: Codable, Sendable { public let state, reason: String }
public struct MachineOccupancy: Codable, Sendable { public let runningRuntimes: UInt64; enum CodingKeys: String, CodingKey { case runningRuntimes = "running_runtimes" } }
public struct MachineTransport: Codable, Sendable { public let `protocol`, status: String; public let lastSuccessAt: String?; enum CodingKeys: String, CodingKey { case `protocol`, status, lastSuccessAt = "last_success_at" } }
public struct MachineResource: Codable, Sendable { public let id, kind, revision, updatedAt, hostID, name, state: String; public let fleetID: String?; public let capacity: MachineCapacity; public let occupancy: MachineOccupancy; public let projects, work: [String]; public let transports: [MachineTransport]; public let runtimeIDs: [String]; public let operational: Operational?; enum CodingKeys: String, CodingKey { case id, kind, revision, updatedAt = "updated_at", hostID = "host_id", name, state, fleetID = "fleet_id", capacity, occupancy, projects, work, transports, runtimeIDs = "runtime_ids", operational } }
public struct DeviceResource: Codable, Sendable { public let id, kind, revision, updatedAt, personID, sessionActor, state, expiresAt: String; public let name: String?; public let scopes: [String]; public let operational: Operational?; enum CodingKeys: String, CodingKey { case id, kind, revision, updatedAt = "updated_at", personID = "person_id", name, sessionActor = "session_actor", state, scopes, expiresAt = "expires_at", operational } }
public struct OperationResource: Codable, Sendable { public let id, kind, revision, updatedAt, component, severity, state, summary: String; public let targets: [String]; public let operational: Operational?; enum CodingKeys: String, CodingKey { case id, kind, revision, updatedAt = "updated_at", component, severity, state, summary, targets, operational } }
public struct HistoryResource: Codable, Sendable { public let id, kind, revision, updatedAt, eventType, occurredAt, summary: String; public let storeIndex: UInt64; public let targets: [String]; public let operational: Operational?; enum CodingKeys: String, CodingKey { case id, kind, revision, updatedAt = "updated_at", eventType = "event_type", occurredAt = "occurred_at", storeIndex = "store_index", summary, targets, operational } }
public struct SessionResource: Codable, Sendable { public let id, kind, revision, updatedAt, ownerID, state, startedAt, timelineCursor: String; public let endedAt: String?; public let usage: UsageSummary?; public let operational: Operational?; enum CodingKeys: String, CodingKey { case id, kind, revision, updatedAt = "updated_at", ownerID = "owner_id", state, startedAt = "started_at", endedAt = "ended_at", timelineCursor = "timeline_cursor", usage, operational } }
public enum Resource: Codable, Sendable, Identifiable {
    case attention(AttentionResource), message(MessageResource), launch(LaunchResource), launchVariant(LaunchVariantResource), launchDecision(LaunchDecisionResource), launchApproval(LaunchApprovalResource), mission(MissionResource), work(WorkResource), agent(AgentResource), runtime(RuntimeResource), observer(ObserverResource), subscription(SubscriptionResource), lane(LaneResource), machine(MachineResource), device(DeviceResource), operation(OperationResource), history(HistoryResource), session(SessionResource), glass(GlassResource)
    private struct Discriminator: Decodable { let kind: String }
    public init(from decoder: Decoder) throws {
        switch try Discriminator(from: decoder).kind {
        case "attention": self = .attention(try AttentionResource(from: decoder))
        case "message": self = .message(try MessageResource(from: decoder))
        case "launch": self = .launch(try LaunchResource(from: decoder))
        case "launch-variant": self = .launchVariant(try LaunchVariantResource(from: decoder))
        case "launch-decision": self = .launchDecision(try LaunchDecisionResource(from: decoder))
        case "launch-approval": self = .launchApproval(try LaunchApprovalResource(from: decoder))
        case "mission": self = .mission(try MissionResource(from: decoder))
        case "work": self = .work(try WorkResource(from: decoder))
        case "agent": self = .agent(try AgentResource(from: decoder))
        case "runtime": self = .runtime(try RuntimeResource(from: decoder))
        case "observer": self = .observer(try ObserverResource(from: decoder))
        case "subscription": self = .subscription(try SubscriptionResource(from: decoder))
        case "lane": self = .lane(try LaneResource(from: decoder))
        case "machine": self = .machine(try MachineResource(from: decoder))
        case "device": self = .device(try DeviceResource(from: decoder))
        case "operation": self = .operation(try OperationResource(from: decoder))
        case "history": self = .history(try HistoryResource(from: decoder))
        case "session": self = .session(try SessionResource(from: decoder))
        case "glass": self = .glass(try GlassResource(from: decoder))
        default: throw DecodingError.dataCorrupted(.init(codingPath: decoder.codingPath, debugDescription: "Unknown Resource kind"))
        }
    }
    public func encode(to encoder: Encoder) throws { switch self { case .attention(let v): try v.encode(to: encoder); case .message(let v): try v.encode(to: encoder); case .launch(let v): try v.encode(to: encoder); case .launchVariant(let v): try v.encode(to: encoder); case .launchDecision(let v): try v.encode(to: encoder); case .launchApproval(let v): try v.encode(to: encoder); case .mission(let v): try v.encode(to: encoder); case .work(let v): try v.encode(to: encoder); case .agent(let v): try v.encode(to: encoder); case .runtime(let v): try v.encode(to: encoder); case .observer(let v): try v.encode(to: encoder); case .subscription(let v): try v.encode(to: encoder); case .lane(let v): try v.encode(to: encoder); case .machine(let v): try v.encode(to: encoder); case .device(let v): try v.encode(to: encoder); case .operation(let v): try v.encode(to: encoder); case .history(let v): try v.encode(to: encoder); case .session(let v): try v.encode(to: encoder); case .glass(let v): try v.encode(to: encoder) } }
    public var id: String { switch self { case .attention(let v): v.id; case .message(let v): v.id; case .launch(let v): v.id; case .launchVariant(let v): v.id; case .launchDecision(let v): v.id; case .launchApproval(let v): v.id; case .mission(let v): v.id; case .work(let v): v.id; case .agent(let v): v.id; case .runtime(let v): v.id; case .observer(let v): v.id; case .subscription(let v): v.id; case .lane(let v): v.id; case .machine(let v): v.id; case .device(let v): v.id; case .operation(let v): v.id; case .history(let v): v.id; case .session(let v): v.id; case .glass(let v): v.id } }
}
public struct ResourcePage: Codable, Sendable { public let kind: String; public let collection: String; public let filters: [String: String]; public let items: [Resource]; public let page: PageInfo; public let sync: SyncNotice? }
public struct SyncNotice: Codable, Sendable { public let state: String; public let peers: [SyncPeer] }
public struct SyncPeer: Codable, Sendable { public let hostID: String; public let peerOnlyEnvelopes, localOnlyEnvelopes: UInt64; public let lastExchangeAt: String?; public let estimatedCatchUpSeconds: UInt64?; public let divergedSince: String?; enum CodingKeys: String, CodingKey { case hostID = "host_id", peerOnlyEnvelopes = "peer_only_envelopes", localOnlyEnvelopes = "local_only_envelopes", lastExchangeAt = "last_exchange_at", estimatedCatchUpSeconds = "estimated_catch_up_seconds", divergedSince = "diverged_since" } }

public enum TimelineRole: String, Codable, Sendable { case system, user, assistant, tool }
public enum TimelineType: String, Codable, Sendable { case message, content, toolCall = "tool_call", toolResult = "tool_result", status, error, usage, redaction, truncation }
public enum TimelineToolStatus: String, Codable, Sendable { case success, error }
public enum TimelineStatus: String, Codable, Sendable { case queued, running, waiting, completed, failed, cancelled }
public enum TimelineUsageSemantics: String, Codable, Sendable { case contextOccupancy = "context_occupancy", sessionCumulative = "session_cumulative", response }
public struct TimelineMessageBody: Codable, Sendable { public let messageID: String; public let replyTo, from, to, title: String?; enum CodingKeys: String, CodingKey { case messageID = "message_id", replyTo = "reply_to", from, to, title } }
public struct TimelineContentBody: Codable, Sendable { public let mediaType: String; public let text: String?; public let attachmentID: String?; enum CodingKeys: String, CodingKey { case mediaType = "media_type", text, attachmentID = "attachment_id" } }
public struct TimelineToolCallBody: Codable, Sendable { public let callID: String; public let name: String; public let arguments: JSONValue; enum CodingKeys: String, CodingKey { case callID = "call_id", name, arguments } }
public struct TimelineToolResultBody: Codable, Sendable { public let callID: String; public let status: TimelineToolStatus; public let mediaType: String; public let content: JSONValue; enum CodingKeys: String, CodingKey { case callID = "call_id", status, mediaType = "media_type", content } }
public struct TimelineStatusBody: Codable, Sendable { public let status: TimelineStatus; public let detail: String? }
public struct TimelineErrorBody: Codable, Sendable { public let code: String; public let message: String; public let retryable: Bool; public let details: [String: JSONValue] }
public struct TimelineAttribution: Codable, Sendable { public let agentID: String; public let missionRunID: String?; public let generationID: String?; public let stepID: String?; enum CodingKeys: String, CodingKey { case agentID = "agent_id", missionRunID = "mission_run_id", generationID = "generation_id", stepID = "step_id" } }
public struct TimelineUsageBody: Codable, Sendable { public let semantics: TimelineUsageSemantics; public let driver: String; public let model: String?; public let inputTokens: UInt64?; public let outputTokens: UInt64?; public let cachedTokens: UInt64?; public let totalTokens: UInt64?; public let contextUsedTokens: UInt64?; public let contextWindowTokens: UInt64?; public let contextUsedPercent: Double?; public let compactions: UInt64?; public let lastCompactionMs: UInt64?; public let lastCompactionTrigger: String?; public let cost: Double?; public let currency: String?; public let attribution: TimelineAttribution; enum CodingKeys: String, CodingKey { case semantics, driver, model, inputTokens = "input_tokens", outputTokens = "output_tokens", cachedTokens = "cached_tokens", totalTokens = "total_tokens", contextUsedTokens = "context_used_tokens", contextWindowTokens = "context_window_tokens", contextUsedPercent = "context_used_percent", compactions, lastCompactionMs = "last_compaction_ms", lastCompactionTrigger = "last_compaction_trigger", cost, currency, attribution } }
public struct TimelineRedactionBody: Codable, Sendable { public let reason: String; public let withheldBytes: UInt64; public let withheldItems: UInt64?; enum CodingKeys: String, CodingKey { case reason, withheldBytes = "withheld_bytes", withheldItems = "withheld_items" } }
public struct TimelineTruncationBody: Codable, Sendable { public let reason: String; public let omittedFromSequence: UInt64; public let omittedToSequence: UInt64; public let continuationCursor: String?; enum CodingKeys: String, CodingKey { case reason, omittedFromSequence = "omitted_from_sequence", omittedToSequence = "omitted_to_sequence", continuationCursor = "continuation_cursor" } }
public enum TimelineBody: Sendable { case message(TimelineMessageBody), content(TimelineContentBody), toolCall(TimelineToolCallBody), toolResult(TimelineToolResultBody), status(TimelineStatusBody), error(TimelineErrorBody), usage(TimelineUsageBody), redaction(TimelineRedactionBody), truncation(TimelineTruncationBody) }
public struct TimelineEntry: Codable, Sendable, Identifiable {
    public let id: String; public let sequence: UInt64; public let revision: UInt; public let timestamp: String; public let role: TimelineRole; public let type: TimelineType; public let isFinal: Bool; public let body: TimelineBody
    enum CodingKeys: String, CodingKey { case id, sequence, revision, timestamp, role, type, isFinal = "final", body }
    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: CodingKeys.self)
        id = try values.decode(String.self, forKey: .id); sequence = try values.decode(UInt64.self, forKey: .sequence); revision = try values.decode(UInt.self, forKey: .revision); timestamp = try values.decode(String.self, forKey: .timestamp); role = try values.decode(TimelineRole.self, forKey: .role); type = try values.decode(TimelineType.self, forKey: .type); isFinal = try values.decode(Bool.self, forKey: .isFinal)
        body = switch type { case .message: .message(try values.decode(TimelineMessageBody.self, forKey: .body)); case .content: .content(try values.decode(TimelineContentBody.self, forKey: .body)); case .toolCall: .toolCall(try values.decode(TimelineToolCallBody.self, forKey: .body)); case .toolResult: .toolResult(try values.decode(TimelineToolResultBody.self, forKey: .body)); case .status: .status(try values.decode(TimelineStatusBody.self, forKey: .body)); case .error: .error(try values.decode(TimelineErrorBody.self, forKey: .body)); case .usage: .usage(try values.decode(TimelineUsageBody.self, forKey: .body)); case .redaction: .redaction(try values.decode(TimelineRedactionBody.self, forKey: .body)); case .truncation: .truncation(try values.decode(TimelineTruncationBody.self, forKey: .body)) }
    }
    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: CodingKeys.self); try values.encode(id, forKey: .id); try values.encode(sequence, forKey: .sequence); try values.encode(revision, forKey: .revision); try values.encode(timestamp, forKey: .timestamp); try values.encode(role, forKey: .role); try values.encode(type, forKey: .type); try values.encode(isFinal, forKey: .isFinal)
        switch body { case .message(let value): try values.encode(value, forKey: .body); case .content(let value): try values.encode(value, forKey: .body); case .toolCall(let value): try values.encode(value, forKey: .body); case .toolResult(let value): try values.encode(value, forKey: .body); case .status(let value): try values.encode(value, forKey: .body); case .error(let value): try values.encode(value, forKey: .body); case .usage(let value): try values.encode(value, forKey: .body); case .redaction(let value): try values.encode(value, forKey: .body); case .truncation(let value): try values.encode(value, forKey: .body) }
    }
}
public struct TimelinePage: Codable, Sendable { public let kind: String; public let sessionID: String; public let items: [TimelineEntry]; public let page: PageInfo; enum CodingKeys: String, CodingKey { case kind, sessionID = "session_id", items, page } }
public struct ConversationChanges: Codable, Sendable { public let kind: String; public let sessionID: String; public let items: [TimelineEntry]; public let nextCursor: String; enum CodingKeys: String, CodingKey { case kind, sessionID = "session_id", items, nextCursor = "next_cursor" } }
public struct ProjectionEvent: Codable, Sendable, Identifiable { public let id: String; public let epoch: String; public let sequence: UInt64; public let previousCursor: String; public let nextCursor: String; public let timestamp: String; public let type: String; public let resourceIDs: [String]; public let snapshotID: String; public let body: [String: JSONValue]; enum CodingKeys: String, CodingKey { case id, epoch, sequence, previousCursor = "previous_cursor", nextCursor = "next_cursor", timestamp, type, resourceIDs = "resource_ids", snapshotID = "snapshot_id", body } }
public struct EventPage: Codable, Sendable { public let kind: String; public let oldestCursor: String; public let resumeCursor: String; public let items: [ProjectionEvent]; public let hasMore: Bool; enum CodingKeys: String, CodingKey { case kind, oldestCursor = "oldest_cursor", resumeCursor = "resume_cursor", items, hasMore = "has_more" } }

public struct Fence: Codable, Sendable {
    public var snapshotID: String; public var subjectRevisions: [String: String]; public var missionGeneration: String?; public var stepDefinition: String?; public var attempt: UInt?; public var readinessEpoch: UInt64?; public var runtimeIncarnation: String?; public var runtimeDesiredRevision: String?; public var terminalSequence: UInt64?; public var previewToken: String?
    public init(snapshotID: String, subjectRevisions: [String: String] = [:]) { self.snapshotID = snapshotID; self.subjectRevisions = subjectRevisions }
    enum CodingKeys: String, CodingKey { case snapshotID = "snapshot_id", subjectRevisions = "subject_revisions", missionGeneration = "mission_generation", stepDefinition = "step_definition", attempt, readinessEpoch = "readiness_epoch", runtimeIncarnation = "runtime_incarnation", runtimeDesiredRevision = "runtime_desired_revision", terminalSequence = "terminal_sequence", previewToken = "preview_token" }
}
public struct ActionRequest: Codable, Sendable {
    public let apiVersion: String; public let id: String; public let type: ActionType; public let idempotencyKey: String; public let fence: Fence; public let parameters: [String: JSONValue]
    private init(id: String, type: ActionType, idempotencyKey: String, fence: Fence, parameters: [String: JSONValue]) { self.apiVersion = st3ClientAPIVersion; self.id = id; self.type = type; self.idempotencyKey = idempotencyKey; self.fence = fence; self.parameters = parameters }
    private init<Parameters: Encodable>(id: String, type: ActionType, idempotencyKey: String, fence: Fence, typedParameters: Parameters) throws {
        let encoded = try JSONEncoder().encode(typedParameters)
        guard case .object(let parameters) = try JSONDecoder().decode(JSONValue.self, from: encoded) else { throw EncodingError.invalidValue(typedParameters, .init(codingPath: [], debugDescription: "Action parameters must encode as an object")) }
        self.init(id: id, type: type, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)
    }
    public static func agentQueueMove(id: String, idempotencyKey: String, fence: Fence, parameters: AgentQueueMoveParameters) throws -> Self { try .init(id: id, type: .agentQueueMove, idempotencyKey: idempotencyKey, fence: fence, typedParameters: parameters) }
    public static func attentionResolve(id: String, idempotencyKey: String, fence: Fence, parameters: AttentionResolveParameters) throws -> Self { try .init(id: id, type: .attentionResolve, idempotencyKey: idempotencyKey, fence: fence, typedParameters: parameters) }
    public static func laneApprove(id: String, idempotencyKey: String, fence: Fence, parameters: LaneChangeParameters) throws -> Self { try .init(id: id, type: .laneApprove, idempotencyKey: idempotencyKey, fence: fence, typedParameters: parameters) }
    public static func laneJoin(id: String, idempotencyKey: String, fence: Fence, parameters: LaneChangeParameters) throws -> Self { try .init(id: id, type: .laneJoin, idempotencyKey: idempotencyKey, fence: fence, typedParameters: parameters) }
    public static func laneLeave(id: String, idempotencyKey: String, fence: Fence, parameters: LaneChangeParameters) throws -> Self { try .init(id: id, type: .laneLeave, idempotencyKey: idempotencyKey, fence: fence, typedParameters: parameters) }
    public static func laneMark(id: String, idempotencyKey: String, fence: Fence, parameters: LaneChangeParameters) throws -> Self { try .init(id: id, type: .laneMark, idempotencyKey: idempotencyKey, fence: fence, typedParameters: parameters) }
    public static func laneMove(id: String, idempotencyKey: String, fence: Fence, parameters: LaneChangeParameters) throws -> Self { try .init(id: id, type: .laneMove, idempotencyKey: idempotencyKey, fence: fence, typedParameters: parameters) }
    public static func launchApprove(id: String, idempotencyKey: String, fence: Fence, parameters: LaunchVariantParameters) throws -> Self { try .init(id: id, type: .launchApprove, idempotencyKey: idempotencyKey, fence: fence, typedParameters: parameters) }
    public static func launchCancel(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) throws -> Self { try .init(id: id, type: .launchCancel, idempotencyKey: idempotencyKey, fence: fence, typedParameters: parameters) }
    public static func launchCreate(id: String, idempotencyKey: String, fence: Fence, parameters: LaunchCreateParameters) throws -> Self { try .init(id: id, type: .launchCreate, idempotencyKey: idempotencyKey, fence: fence, typedParameters: parameters) }
    public static func launchPreview(id: String, idempotencyKey: String, fence: Fence, parameters: LaunchVariantParameters) throws -> Self { try .init(id: id, type: .launchPreview, idempotencyKey: idempotencyKey, fence: fence, typedParameters: parameters) }
    public static func launchRevise(id: String, idempotencyKey: String, fence: Fence, parameters: LaunchReviseParameters) throws -> Self { try .init(id: id, type: .launchRevise, idempotencyKey: idempotencyKey, fence: fence, typedParameters: parameters) }
    public static func messageClose(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) throws -> Self { try .init(id: id, type: .messageClose, idempotencyKey: idempotencyKey, fence: fence, typedParameters: parameters) }
    public static func messageRead(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) throws -> Self { try .init(id: id, type: .messageRead, idempotencyKey: idempotencyKey, fence: fence, typedParameters: parameters) }
    public static func messageSend(id: String, idempotencyKey: String, fence: Fence, parameters: MessageSendParameters) throws -> Self { try .init(id: id, type: .messageSend, idempotencyKey: idempotencyKey, fence: fence, typedParameters: parameters) }
    public static func missionApproveRevision(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) throws -> Self { try .init(id: id, type: .missionApproveRevision, idempotencyKey: idempotencyKey, fence: fence, typedParameters: parameters) }
    public static func missionCancel(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) throws -> Self { try .init(id: id, type: .missionCancel, idempotencyKey: idempotencyKey, fence: fence, typedParameters: parameters) }
    public static func missionCancelRevision(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) throws -> Self { try .init(id: id, type: .missionCancelRevision, idempotencyKey: idempotencyKey, fence: fence, typedParameters: parameters) }
    public static func missionRevise(id: String, idempotencyKey: String, fence: Fence, parameters: MissionReviseParameters) throws -> Self { try .init(id: id, type: .missionRevise, idempotencyKey: idempotencyKey, fence: fence, typedParameters: parameters) }
    public static func missionStart(id: String, idempotencyKey: String, fence: Fence, parameters: MissionStartParameters) throws -> Self { try .init(id: id, type: .missionStart, idempotencyKey: idempotencyKey, fence: fence, typedParameters: parameters) }
    public static func pairingRevoke(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) throws -> Self { try .init(id: id, type: .pairingRevoke, idempotencyKey: idempotencyKey, fence: fence, typedParameters: parameters) }
    public static func reviewApprove(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) throws -> Self { try .init(id: id, type: .reviewApprove, idempotencyKey: idempotencyKey, fence: fence, typedParameters: parameters) }
    public static func reviewReject(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) throws -> Self { try .init(id: id, type: .reviewReject, idempotencyKey: idempotencyKey, fence: fence, typedParameters: parameters) }
    public static func reviewRequestChanges(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) throws -> Self { try .init(id: id, type: .reviewRequestChanges, idempotencyKey: idempotencyKey, fence: fence, typedParameters: parameters) }
    public static func runtimeContextClear(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) throws -> Self { try .init(id: id, type: .runtimeContextClear, idempotencyKey: idempotencyKey, fence: fence, typedParameters: parameters) }
    public static func runtimeReset(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) throws -> Self { try .init(id: id, type: .runtimeReset, idempotencyKey: idempotencyKey, fence: fence, typedParameters: parameters) }
    public static func runtimeRestart(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) throws -> Self { try .init(id: id, type: .runtimeRestart, idempotencyKey: idempotencyKey, fence: fence, typedParameters: parameters) }
    public static func runtimeSignal(id: String, idempotencyKey: String, fence: Fence, parameters: RuntimeSignalParameters) throws -> Self { try .init(id: id, type: .runtimeSignal, idempotencyKey: idempotencyKey, fence: fence, typedParameters: parameters) }
    public static func runtimeStop(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) throws -> Self { try .init(id: id, type: .runtimeStop, idempotencyKey: idempotencyKey, fence: fence, typedParameters: parameters) }
    public static func sessionImport(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) throws -> Self { try .init(id: id, type: .sessionImport, idempotencyKey: idempotencyKey, fence: fence, typedParameters: parameters) }
    public static func terminalAttach(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) throws -> Self { try .init(id: id, type: .terminalAttach, idempotencyKey: idempotencyKey, fence: fence, typedParameters: parameters) }
    public static func terminalDetach(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) throws -> Self { try .init(id: id, type: .terminalDetach, idempotencyKey: idempotencyKey, fence: fence, typedParameters: parameters) }
    public static func terminalInput(id: String, idempotencyKey: String, fence: Fence, parameters: TerminalInputParameters) throws -> Self { try .init(id: id, type: .terminalInput, idempotencyKey: idempotencyKey, fence: fence, typedParameters: parameters) }
    public static func terminalResize(id: String, idempotencyKey: String, fence: Fence, parameters: TerminalResizeParameters) throws -> Self { try .init(id: id, type: .terminalResize, idempotencyKey: idempotencyKey, fence: fence, typedParameters: parameters) }
    public static func workAsk(id: String, idempotencyKey: String, fence: Fence, parameters: PersonAskParameters) throws -> Self { try .init(id: id, type: .workAsk, idempotencyKey: idempotencyKey, fence: fence, typedParameters: parameters) }
    public static func workCancelAsk(id: String, idempotencyKey: String, fence: Fence, parameters: PersonStepParameters) throws -> Self { try .init(id: id, type: .workCancelAsk, idempotencyKey: idempotencyKey, fence: fence, typedParameters: parameters) }
    public static func workClaim(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) throws -> Self { try .init(id: id, type: .workClaim, idempotencyKey: idempotencyKey, fence: fence, typedParameters: parameters) }
    public static func workComplete(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) throws -> Self { try .init(id: id, type: .workComplete, idempotencyKey: idempotencyKey, fence: fence, typedParameters: parameters) }
    public static func workDone(id: String, idempotencyKey: String, fence: Fence, parameters: PersonStepParameters) throws -> Self { try .init(id: id, type: .workDone, idempotencyKey: idempotencyKey, fence: fence, typedParameters: parameters) }
    public static func workFail(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) throws -> Self { try .init(id: id, type: .workFail, idempotencyKey: idempotencyKey, fence: fence, typedParameters: parameters) }
    public static func workProgress(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) throws -> Self { try .init(id: id, type: .workProgress, idempotencyKey: idempotencyKey, fence: fence, typedParameters: parameters) }
    public static func workPublishMission(id: String, idempotencyKey: String, fence: Fence, parameters: WorkPublishMissionParameters) throws -> Self { try .init(id: id, type: .workPublishMission, idempotencyKey: idempotencyKey, fence: fence, typedParameters: parameters) }
    public static func workRelease(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) throws -> Self { try .init(id: id, type: .workRelease, idempotencyKey: idempotencyKey, fence: fence, typedParameters: parameters) }
    public static func workRenew(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) throws -> Self { try .init(id: id, type: .workRenew, idempotencyKey: idempotencyKey, fence: fence, typedParameters: parameters) }
    public static func workRetry(id: String, idempotencyKey: String, fence: Fence, parameters: WorkRetryParameters) throws -> Self { try .init(id: id, type: .workRetry, idempotencyKey: idempotencyKey, fence: fence, typedParameters: parameters) }
    enum CodingKeys: String, CodingKey { case apiVersion = "api_version", id, type, idempotencyKey = "idempotency_key", fence, parameters }
}

public struct PersonAskParameters: Codable, Sendable { public var personID, title, reason: String; public var stepID, newRun: String?; public init(personID: String, title: String, reason: String, stepID: String? = nil, newRun: String? = nil) { self.personID = personID; self.title = title; self.reason = reason; self.stepID = stepID; self.newRun = newRun }; enum CodingKeys: String, CodingKey { case personID = "person_id", title, reason, stepID = "step_id", newRun = "new_run" } }
public struct PersonStepParameters: Codable, Sendable { public var targetID, summary, episode: String; public var evidence: [String]; public init(targetID: String, summary: String, episode: String, evidence: [String] = []) { self.targetID = targetID; self.summary = summary; self.episode = episode; self.evidence = evidence }; enum CodingKeys: String, CodingKey { case targetID = "target_id", summary, episode, evidence } }
public struct TargetParameters: Codable, Sendable { public var targetID: String; public var reason: String?; public var summary: String?; public var evidence: [String]; public init(targetID: String, reason: String? = nil, summary: String? = nil, evidence: [String] = []) { self.targetID = targetID; self.reason = reason; self.summary = summary; self.evidence = evidence }; enum CodingKeys: String, CodingKey { case targetID = "target_id", reason, summary, evidence } }
public struct WorkRetryParameters: Codable, Sendable { public var targetID: String; public var reason: String; public init(targetID: String, reason: String) { self.targetID = targetID; self.reason = reason }; enum CodingKeys: String, CodingKey { case targetID = "target_id", reason } }
public struct AttentionResolveParameters: Codable, Sendable { public var attentionID: String; public var outcome: String; public var reason: String?; public init(attentionID: String, outcome: String, reason: String? = nil) { self.attentionID = attentionID; self.outcome = outcome; self.reason = reason }; enum CodingKeys: String, CodingKey { case attentionID = "attention_id", outcome, reason } }
public struct MessageSendParameters: Codable, Sendable { public var to: String; public var content: String; public var title: String?; public var inReplyTo: String?; public var sessionID: String?; public var tags: [String]; public init(to: String, content: String, title: String? = nil, inReplyTo: String? = nil, sessionID: String? = nil, tags: [String] = []) { self.to = to; self.content = content; self.title = title; self.inReplyTo = inReplyTo; self.sessionID = sessionID; self.tags = tags }; enum CodingKeys: String, CodingKey { case to, content, title, inReplyTo = "in_reply_to", sessionID = "session_id", tags } }
public struct LaunchTarget: Codable, Sendable {
    public enum Kind: String, Codable, Sendable { case newMission = "new-mission", missionRun = "mission-run" }
    public let kind: Kind
    public let missionID: String?
    public let workspace: String?
    public let missionRunID: String?
    public let generationID: String?
    private init(kind: Kind, missionID: String? = nil, workspace: String? = nil, missionRunID: String? = nil, generationID: String? = nil) { self.kind = kind; self.missionID = missionID; self.workspace = workspace; self.missionRunID = missionRunID; self.generationID = generationID }
    public static func newMission(_ missionID: String, workspace: String) -> Self { .init(kind: .newMission, missionID: missionID, workspace: workspace) }
    public static func missionRun(_ missionRunID: String, generationID: String) -> Self { .init(kind: .missionRun, missionRunID: missionRunID, generationID: generationID) }
    enum CodingKeys: String, CodingKey { case kind = "type", missionID = "mission_id", workspace, missionRunID = "mission_run_id", generationID = "generation_id" }
}
public struct LaunchCreateParameters: Codable, Sendable { public var title: String; public var request: String; public var target: LaunchTarget; public var provider: PlannerProvider?; public var model, effort: String?; public init(title: String, request: String, target: LaunchTarget, provider: PlannerProvider? = nil, model: String? = nil, effort: String? = nil) { self.title = title; self.request = request; self.target = target; self.provider = provider; self.model = model; self.effort = effort } }
public struct LaunchReviseParameters: Codable, Sendable { public var launchID: String; public var feedback: String; public init(launchID: String, feedback: String) { self.launchID = launchID; self.feedback = feedback }; enum CodingKeys: String, CodingKey { case launchID = "launch_id", feedback } }
public struct LaunchVariantParameters: Codable, Sendable { public var launchID: String; public var variantID: String; public init(launchID: String, variantID: String) { self.launchID = launchID; self.variantID = variantID }; enum CodingKeys: String, CodingKey { case launchID = "launch_id", variantID = "variant_id" } }
public struct MissionStartParameters: Codable, Sendable { public var missionID: String; public var workspace: String; public var inputs: [String: String]; public init(missionID: String, workspace: String, inputs: [String: String] = [:]) { self.missionID = missionID; self.workspace = workspace; self.inputs = inputs }; enum CodingKeys: String, CodingKey { case missionID = "mission_id", workspace, inputs } }
public struct MissionReviseParameters: Codable, Sendable { public var missionRunID: String; public var launchID: String; public init(missionRunID: String, launchID: String) { self.missionRunID = missionRunID; self.launchID = launchID }; enum CodingKeys: String, CodingKey { case missionRunID = "mission_run_id", launchID = "launch_id" } }
public struct WorkPublishMissionParameters: Codable, Sendable { public var targetID: String; public var name: String; public var mission: [String: JSONValue]; public init(targetID: String, name: String, mission: [String: JSONValue]) { self.targetID = targetID; self.name = name; self.mission = mission }; enum CodingKeys: String, CodingKey { case targetID = "target_id", name, mission } }
public struct AgentQueueMoveParameters: Codable, Sendable { public var agentID: String; public var missionRunID: String; public var placement: AgentQueuePlacement; public var anchorRunID: String?; public var reason: String?; public init(agentID: String, missionRunID: String, placement: AgentQueuePlacement, anchorRunID: String? = nil, reason: String? = nil) { self.agentID = agentID; self.missionRunID = missionRunID; self.placement = placement; self.anchorRunID = anchorRunID; self.reason = reason }; enum CodingKeys: String, CodingKey { case agentID = "agent_id", missionRunID = "mission_run_id", placement, anchorRunID = "anchor_run_id", reason } }
public struct LaneChangeParameters: Codable, Sendable { public var laneID: String; public var entryID: String; public var reason: String?; public var outcome: String?; public var placement: AgentQueuePlacement?; public var anchorID: String?; public var state: String?; public var detail: String?; public var head: String?; public init(laneID: String, entryID: String, reason: String? = nil, outcome: String? = nil, placement: AgentQueuePlacement? = nil, anchorID: String? = nil, state: String? = nil, detail: String? = nil, head: String? = nil) { self.laneID = laneID; self.entryID = entryID; self.reason = reason; self.outcome = outcome; self.placement = placement; self.anchorID = anchorID; self.state = state; self.detail = detail; self.head = head }; enum CodingKeys: String, CodingKey { case laneID = "lane_id", entryID = "entry_id", reason, outcome, placement, anchorID = "anchor_id", state, detail, head } }
public struct RuntimeSignalParameters: Codable, Sendable { public var targetID: String; public var signal: String; public init(targetID: String, signal: String) { self.targetID = targetID; self.signal = signal }; enum CodingKeys: String, CodingKey { case targetID = "target_id", signal } }
public enum TerminalInputMode: String, Codable, Sendable { case line, raw, key }
public struct TerminalInputParameters: Codable, Sendable { public var terminalID: String; public var mode: TerminalInputMode; public var value: String; public init(terminalID: String, mode: TerminalInputMode, value: String) { self.terminalID = terminalID; self.mode = mode; self.value = value }; enum CodingKeys: String, CodingKey { case terminalID = "terminal_id", mode, value } }
public struct TerminalResizeParameters: Codable, Sendable { public var terminalID: String; public var rows: UInt16; public var columns: UInt16; public init(terminalID: String, rows: UInt16, columns: UInt16) { self.terminalID = terminalID; self.rows = rows; self.columns = columns }; enum CodingKeys: String, CodingKey { case terminalID = "terminal_id", rows, columns } }
public struct TerminalAttachment: Codable, Sendable { public let attachmentID: String; public let terminalID: String; public let runtimeIncarnation: String; public let ownerHostID: String; public let streamURL: String; public let streamCapability: String?; public let state: String; public let expiresAt: String; enum CodingKeys: String, CodingKey { case attachmentID = "attachment_id", terminalID = "terminal_id", runtimeIncarnation = "runtime_incarnation", ownerHostID = "owner_host_id", streamURL = "stream_url", streamCapability = "stream_capability", state, expiresAt = "expires_at" } }
public struct ActionResult: Codable, Sendable { public let kind: String; public let actionID: String; public let operationID: String; public let status: String; public let affectedIDs: [String]; public let snapshotID: String; public let terminalAttachment: TerminalAttachment?; enum CodingKeys: String, CodingKey { case kind, actionID = "action_id", operationID = "operation_id", status, affectedIDs = "affected_ids", snapshotID = "snapshot_id", terminalAttachment = "terminal_attachment" } }

public struct PairingBegin: Codable, Sendable { public let apiVersion: String; public let deviceName: String; public let personID: String; public let fullControl: Bool?; public init(apiVersion: String, deviceName: String, personID: String, fullControl: Bool? = nil) { self.apiVersion = apiVersion; self.deviceName = deviceName; self.personID = personID; self.fullControl = fullControl }; enum CodingKeys: String, CodingKey { case apiVersion = "api_version", deviceName = "device_name", personID = "person_id", fullControl = "full_control" } }
public struct PairingChallenge: Codable, Sendable { public let kind: String; public let pairingID: String; public let code: String; public let expiresAt: String; enum CodingKeys: String, CodingKey { case kind, pairingID = "pairing_id", code, expiresAt = "expires_at" } }
public struct PairingComplete: Codable, Sendable { public let apiVersion: String; public let code: String; public let devicePublicKey: String; enum CodingKeys: String, CodingKey { case apiVersion = "api_version", code, devicePublicKey = "device_public_key" } }
public struct PairedSession: Codable, Sendable { public let kind: String; public let deviceID: String; public let personID: String; public let sessionActor: String; public let credential: String; public let scopes: [String]; public let expiresAt: String; enum CodingKeys: String, CodingKey { case kind, deviceID = "device_id", personID = "person_id", sessionActor = "session_actor", credential, scopes, expiresAt = "expires_at" } }

public struct TerminalLine: Codable, Sendable { public let row: Int; public let text: String; public let runs: [TerminalRun]; public let redacted: Bool; public let truncated: Bool }
/// Styled text from column zero; absent colors and flags are the terminal defaults.
public struct TerminalRun: Codable, Sendable { public let text: String; public let fg: TerminalColor?; public let bg: TerminalColor?; public let bold: Bool?; public let dim: Bool?; public let italic: Bool?; public let underline: Bool?; public let inverse: Bool? }
/// A palette index (0-255) or a `#rrggbb` color.
public enum TerminalColor: Codable, Sendable, Equatable {
    case palette(Int)
    case rgb(String)
    public init(from decoder: Decoder) throws { let container = try decoder.singleValueContainer(); if let index = try? container.decode(Int.self) { self = .palette(index) } else { self = .rgb(try container.decode(String.self)) } }
    public func encode(to encoder: Encoder) throws { var container = encoder.singleValueContainer(); switch self { case .palette(let index): try container.encode(index); case .rgb(let hex): try container.encode(hex) } }
}
public struct TerminalCursor: Codable, Sendable { public let row: Int; public let column: Int; public let visible: Bool; public let style: String; public let blinking: Bool }
public struct TerminalModes: Codable, Sendable { public let alternateScreen: Bool; public let applicationCursor: Bool; public let applicationKeypad: Bool; public let bracketedPaste: Bool; public let focusEvents: Bool; public let mouseTracking: String; public let mouseEncoding: String; enum CodingKeys: String, CodingKey { case alternateScreen = "alternate_screen", applicationCursor = "application_cursor", applicationKeypad = "application_keypad", bracketedPaste = "bracketed_paste", focusEvents = "focus_events", mouseTracking = "mouse_tracking", mouseEncoding = "mouse_encoding" } }
public struct TerminalScreen: Codable, Sendable { public let kind: String; public let terminalID: String; public let runtimeIncarnation: String; public let revision: String; public let rows: Int; public let columns: Int; public let cursor: TerminalCursor; public let title: String; public let modes: TerminalModes; public let lines: [TerminalLine]; public let nextSequence: UInt64; public let truncated: Bool; enum CodingKeys: String, CodingKey { case kind, terminalID = "terminal_id", runtimeIncarnation = "runtime_incarnation", revision, rows, columns, cursor, title, modes, lines, nextSequence = "next_sequence", truncated } }

public enum GlassSplit: String, Codable, Sendable { case right, below }
public indirect enum GlassLayout: Codable, Sendable {
    case pane(String), split(GlassSplit, [GlassLayout])
    enum CodingKeys: String, CodingKey { case pane, split, children }
    public init(from decoder: Decoder) throws {
        let box = try decoder.container(keyedBy: CodingKeys.self)
        if let pane = try box.decodeIfPresent(String.self, forKey: .pane) { self = .pane(pane) }
        else { let children = try box.decode([GlassLayout].self, forKey: .children); guard children.count == 2 else { throw DecodingError.dataCorruptedError(forKey: .children, in: box, debugDescription: "A split needs two children") }; self = .split(try box.decode(GlassSplit.self, forKey: .split), children) }
    }
    public func encode(to encoder: Encoder) throws { var box = encoder.container(keyedBy: CodingKeys.self); switch self { case .pane(let pane): try box.encode(pane, forKey: .pane); case .split(let split, let children): guard children.count == 2 else { throw EncodingError.invalidValue(children, .init(codingPath: encoder.codingPath, debugDescription: "A split needs two children")) }; try box.encode(split, forKey: .split); try box.encode(children, forKey: .children) } }
}
public struct GlassTab: Codable, Sendable { public var title: String?; public var layout: GlassLayout; public init(title: String? = nil, layout: GlassLayout) { self.title = title; self.layout = layout } }
public struct GlassBody: Codable, Sendable { public var name: String; public var tabs: [GlassTab]; public init(name: String, tabs: [GlassTab]) { self.name = name; self.tabs = tabs } }
public struct GlassResource: Codable, Sendable, Identifiable {
    public let id: String
    public let kind: String
    public let revision: String
    public let updatedAt: String
    public let body: GlassBody?
    public let deleted: Bool
    public let baseRevision: String?
    public let replacedRevision: String?
    enum CodingKeys: String, CodingKey { case id, kind, revision, body, deleted, updatedAt = "updated_at", baseRevision = "base_revision", replacedRevision = "replaced_revision" }
}
public typealias Glass = GlassResource
public struct GlassPut: Codable, Sendable {
    public let body: GlassBody
    public let baseRevision: String?
    public init(body: GlassBody, baseRevision: String?) { self.body = body; self.baseRevision = baseRevision }
    enum CodingKeys: String, CodingKey { case body, baseRevision = "base_revision" }
    public func encode(to encoder: Encoder) throws { var box = encoder.container(keyedBy: CodingKeys.self); try box.encode(body, forKey: .body); try box.encode(baseRevision, forKey: .baseRevision) }
}
public struct GlassDelete: Codable, Sendable {
    public let baseRevision: String?
    public init(baseRevision: String?) { self.baseRevision = baseRevision }
    enum CodingKeys: String, CodingKey { case baseRevision = "base_revision" }
    public func encode(to encoder: Encoder) throws { var box = encoder.container(keyedBy: CodingKeys.self); try box.encode(baseRevision, forKey: .baseRevision) }
}
public struct GlassCollectionFrame: Codable, Sendable {
    public let kind: String
    public let id: String?
    public let snapshot: Snapshot?
    public let items: [Glass]?
    public let upserts: [Glass]?
    public let removes: [String]?
    public let order: [String]?
    public let hasMore: Bool?
    public let code: String?
    public let message: String?
    enum CodingKeys: String, CodingKey { case kind, id, snapshot, items, upserts, removes, order, code, message, hasMore = "has_more" }
}
