/** Shared assistant-ui presentation and external-store boundary. Applications own transport and state. */
export * from './EmbraceRuntime.tsx'
export * from './EmbraceThread.tsx'
export * from './EmbraceScrollViewport.tsx'
export * from './composition/Transcript.tsx'
export * from './composition/TranscriptFeedback.tsx'
export * from './EmbraceComposer.tsx'
export * from './EmbraceToolCall.tsx'
export * from './EmbraceToolPreview.tsx'
export * from './EmbraceVirtualConversation.tsx'
export * from './embrace-converter.ts'
export type { SendState, TextItem } from './embrace-data/model.ts'
export type { Draft, DraftToken, MentionToken, CommandToken, SerializedDraft, SlashCommand, SlashCommandId } from './embrace-composer/draft.ts'

/** Reusable round-2 live composition primitives; transport stays application-owned. */
export { AgentRow, StatusGlyph } from './composition/Sidebar.tsx'
export { ThreadHeader, ResizableSplit } from './composition/Shell.tsx'
export { TerminalSurface } from './terminal/TerminalSurface'
export { TerminalDrawer } from './terminal/TerminalDrawer'
export { resolveTerminalColor, createTerminalPalette } from './terminal/terminal-palette'
export type { TerminalSurfaceProps, TerminalSurfaceHandle, TerminalDrawerProps, TerminalPalette, TerminalFont, TerminalConnection, TerminalColorInput, TerminalScreen } from './terminal/terminal-types'
export { DiffPanel } from './composition/DiffPanel.tsx'
export type { DiffPanelProps, DiffFile, DiffTurn, DiffRevealRequest } from './composition/DiffPanel.tsx'
export { Markdown, ResourceChip, HighlightedSource, completeStreamingTail } from './composition/Markdown.tsx'
export type { MarkdownProps, MarkdownImageResolution, MarkdownImageResolver, MarkdownImageOpener, InlineResource, InlineReferenceRenderer } from './composition/Markdown.tsx'
export { ThinkingEntry } from './composition/ThinkingEntry.tsx'
export { ErrorOverlay, ErrorOverlayHost, useErrorOverlaySurface } from './composition/ErrorOverlay.tsx'
export type { ErrorOverlayNotice } from './composition/ErrorOverlay.tsx'
export { colorVars, typeVars, radiusVars, spaceVars, geometryVars, geometryNumbers } from './composition-tokens.stylex.ts'
export { lightTheme as compositionLightTheme } from './composition-theme.ts'
export { darkTheme as assistantDarkTheme } from './embrace-theme.ts'
export { toolDiffs } from './embrace-tool-preview.ts'
export type { AgentRowData, AgentStatus } from './composition-model.ts'

export { liveComposerDarkTheme, liveAccentTheme } from './embrace-theme.ts'

export { Icon as CompositionIcon } from './composition/Icons'
export { Button as CompositionButton, IconButton as CompositionIconButton } from './composition/Controls'

/** Controlled sidebar row; the host owns clock and data. */
export { SidebarAgentRow, AgentHoverCard, sidebarRowDescription } from './sidebar/SidebarAgentRow.tsx'
export { SidebarStatus } from './sidebar/SidebarStatus.tsx'
export type { SidebarAgentRow as SidebarAgentRowData, SidebarUsage, SidebarDuration, SidebarLastTurn, AgentStatus as SidebarAgentStatus } from './sidebar/model.ts'

export { ResourceCardV1, ResourceChipV1 } from './resources/ResourceCardV1.tsx'
export type { ResourceData, ResourceFile, ResourceMetadata } from './resources/resource-model.ts'

/** Required controlled WF-1; fixture/demo actions are excluded. */
export { WorkLogV1 } from './taste/WorkLogV1.tsx'
export type { WorkLogCallDetailRenderer } from './taste/WorkLogV1.tsx'
export * from './taste/work-log.ts'

/** Host-controlled workspace and composer; fixtures and performance instrumentation stay internal. */
export { Workbench, PaneHost } from './workbench/Workbench.tsx'
export type { WorkbenchProps } from './workbench/Workbench.tsx'
export type { WorkbenchResources, ThreadResource, ThreadControls, DiffResource, WorkbenchPane, WorkbenchLayout } from './workbench/workbench-model.ts'
export type { WorkbenchAppearance, WorkbenchPaneDetails } from './workbench/workbench-appearance.ts'
export { AgentDropSurface } from './workbench/AgentDropSurface.tsx'
export { AGENT_DRAG_MIME, agentPaneKey, openAgentAtPath } from './workbench/agent-drag.ts'
export type { AgentPlacement } from './workbench/agent-drag.ts'
export type { TerminalCapability, TerminalOutputLine, TerminalSession, TerminalFrame } from './workbench/terminal-model.ts'
export { Composer } from './composition/Composer.tsx'
export type { ComposerProps } from './composition/Composer.tsx'
export { ComposerSession } from './composer-session/ComposerSession.tsx'
export type { ComposerSessionProps, ComposerLayout, RunningBehavior, MentionMode, TargetMode } from './composer-session/ComposerSession.tsx'
export { EffortPicker, unknownEffort, messageEffort } from './embrace-composer/EffortPicker.tsx'
export type { EffortControl } from './embrace-composer/EffortPicker.tsx'
