import {mkdtemp,rm,mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {resolve} from 'node:path';
const st=process.env.ST_SMOKE_BIN,daemon=process.env.ST_SMOKE_DAEMON,omp=process.env.OMP_NATIVE_BIN;
if(!st||!daemon||!omp)throw Error('ST_SMOKE_BIN, ST_SMOKE_DAEMON, OMP_NATIVE_BIN required');
const root=await mkdtemp(resolve(tmpdir(),'owner-native-smoke-'));await mkdir(root+'/agent');await mkdir(root+'/sessions');
const socket=root+'/daemon.sock';const env=Object.fromEntries(Object.entries(process.env).filter(([k])=>!k.startsWith('ST_')&&!k.startsWith('ST3_')&&!k.startsWith('AGENT_')));
let delay=2000;const server=Bun.serve({port:0,hostname:'127.0.0.1',fetch:async req=>{await req.json();await Bun.sleep(delay);const chunk={id:'smoke',object:'chat.completion.chunk',created:1,model:'native-smoke',choices:[{index:0,delta:{role:'assistant',content:'complete'},finish_reason:null}]};const end={...chunk,choices:[{index:0,delta:{},finish_reason:'stop'}],usage:{prompt_tokens:1,completion_tokens:1,total_tokens:2}};return new Response(`data: ${JSON.stringify(chunk)}\n\ndata: ${JSON.stringify(end)}\n\ndata: [DONE]\n\n`,{headers:{'content-type':'text/event-stream'}});}});
const d=Bun.spawn([daemon,root],{env,stdin:'ignore',stdout:'pipe',stderr:'pipe'});const daemonError=new Response(d.stderr).text();
let native;let log='';let driverErrors='';
const deadline=setTimeout(()=>{native?.kill();d.kill();},45000);
const request=async(path,body,person=true)=>{const r=await fetch('http://localhost'+path,{unix:socket,method:body?'POST':'GET',headers:{'content-type':'application/json',...(person?{'x-st3-person':'person/operator'}:{})},...(body?{body:JSON.stringify(body)}:{})});const v=await r.json();return {status:r.status,value:v.value,error:v};};
const poll=async(fn,label)=>{for(let i=0;i<250;i++){const value=await fn();if(value)return value;await Bun.sleep(40);}throw Error('Timed out '+label);};
const subject='agent/control-smoke';
const read=async()=>{const r=await request('/v1/client/harness-queue/'+encodeURIComponent(subject));if(r.status!==200)throw Error(JSON.stringify(r));return r.value;};
const receipt=async(operation)=>{const r=await request('/v1/client/harness-control-receipts/'+encodeURIComponent(operation)+'?subject='+encodeURIComponent(subject));if(r.status!==200)throw Error(JSON.stringify(r));return r.value;};
const action=async(key,mutation,bindingOverride,revisionOverride,person=true)=>{const q=await read();const cap=await request('/v1/client/capabilities');const binding=bindingOverride??q.native.binding;const body={api_version:'st3.client.v0',id:'action/'+key,type:'harness.queue.mutate',idempotency_key:'owner-smoke-operation-'+key,fence:{snapshot_id:cap.error.snapshot.id,runtime_incarnation:binding.incarnation_id,runtime_desired_revision:binding.desired_revision},parameters:{subject,binding,queue_revision:revisionOverride??q.queue.revision,mutation}};return {...await request('/v1/client/actions',body,person),body};};
try {
 await poll(async()=>{try{return (await request('/v1/health')).status===200;}catch{return false;}},'daemon');
 native=Bun.spawn([omp,'--mode','rpc','--no-ui','--no-tools','--no-lsp','--no-extensions','--no-skills','--no-rules','--no-title','--no-session','--extension',resolve(import.meta.dir,'owner-extension.ts'),'--model','control-smoke/native-initial','--thinking','low'],{env:{...env,PI_CODING_AGENT_DIR:root+'/profile',ST_SMOKE_BIN:st,SMOKE_SOCKET:socket,SMOKE_ROOT:root,SMOKE_BASE_URL:`http://127.0.0.1:${server.port}/v1`},stdin:'pipe',stdout:'pipe',stderr:'pipe'});
 const out=(async()=>{for await(const bytes of native.stdout){const text=new TextDecoder().decode(bytes);log+=text;process.stdout.write(text);}})();
 const err=(async()=>{driverErrors=await new Response(native.stderr).text();})();
 await poll(async()=>{const q=await read();return q.native?.input_supported&&q.native.idle?q:false;},'native initial idle binding');
 const models=await request('/v1/client/harness-models/'+encodeURIComponent(subject)+'?limit=1');
 if(models.status!==200||models.value.choices[0]?.provider!=='control-smoke'||!models.value.cursor)throw Error('Bounded model catalog unavailable');
 const nextModels=await request('/v1/client/harness-models/'+encodeURIComponent(subject)+'?cursor='+encodeURIComponent(models.value.cursor)+'&limit=1');
 if(nextModels.status!==200||nextModels.value.choices[0]?.id!=='native-smoke')throw Error('Model cursor did not preserve catalog order');
 const modelQueue=await read();const cap=await request('/v1/client/capabilities');const binding=modelQueue.native.binding;
 const modelBody={api_version:'st3.client.v0',id:'action/model',type:'harness.model.set',idempotency_key:'owner-smoke-model',fence:{snapshot_id:cap.error.snapshot.id,runtime_incarnation:binding.incarnation_id,runtime_desired_revision:binding.desired_revision},parameters:{subject,binding,model_revision:modelQueue.native.models.revision,provider:'control-smoke',model_id:'native-smoke',effort:'high'}};
 const modelAction=await request('/v1/client/actions',modelBody);if(modelAction.status!==200||modelAction.value.status!=='accepted')throw Error('Model action not accepted '+JSON.stringify(modelAction));
 const modelReceipt=await poll(async()=>{const r=await receipt(modelAction.value.operation_id);return r.status==='applied'?r:false;},'durable model receipt');
 if(modelReceipt.result?.id!=='native-smoke'||modelReceipt.result?.effective_effort!=='high'||!modelReceipt.model_revision)throw Error('Model receipt lacks exact native proof');
 const unauthorized=await action('unauthorized',{type:'enqueue',content:'deny',lane:'steer'},undefined,undefined,false);if(unauthorized.status!==403)throw Error('Unauthorized native write admitted');
 native.stdin.write(JSON.stringify({type:'prompt',id:'busy',message:'busy seed'})+'\n');native.stdin.flush();
 await poll(async()=>!(await read()).native.idle,'native busy');
 const a=await action('a',{type:'enqueue',content:'same text',lane:'follow_up'});const b=await action('b',{type:'enqueue',content:'same text',lane:'follow_up'});const c=await action('c',{type:'enqueue',content:'same text',lane:'follow_up'});
 if([a,b,c].some(r=>r.status!==200||r.value.status!=='accepted'))throw Error('Input not owner accepted');
 const aid=a.value.harness_control.entry_id,bid=b.value.harness_control.entry_id,cid=c.value.harness_control.entry_id;
 if(new Set([aid,bid,cid]).size!==3)throw Error('Identical input identity collision');
 for(const [key,mutation] of [['move',{type:'move',entry_id:cid,before_id:bid}],['replace',{type:'replace',entry_id:bid,content:'replacement text'}],['cancel-a',{type:'cancel',entry_id:aid}],['promote',{type:'promote',entry_id:bid}],['cancel-c',{type:'cancel',entry_id:cid}]]){const r=await action(key,mutation);if(r.status!==200||r.value.status!=='applied')throw Error(JSON.stringify(r));}
 const q=await read();const stale=await action('stale-turn',{type:'enqueue',content:'stale',lane:'steer'},{...q.native.binding,turn_id:'stale-turn'});if(stale.status<400)throw Error('Stale native turn admitted');
 const badRevision=await action('stale-revision',{type:'enqueue',content:'stale',lane:'steer'},undefined,0);if(badRevision.status<400)throw Error('Stale queue revision admitted');
 const applied=await poll(async()=>{const r=await receipt(b.value.operation_id);return r.status==='applied'?r:false;},'exact native admitted receipt');
 if(!['message_start','message_end'].includes(applied.result?.native_event)||applied.entry_id!==bid)throw Error('Native proof not exact');
 const durable=await receipt(b.value.operation_id);if(durable.status!=='applied'||durable.entry_id!==bid||durable.result?.native_event!==applied.result.native_event)throw Error('Queue receipt GET lost proof');
 const wrongSubject=await request('/v1/client/harness-control-receipts/'+encodeURIComponent(b.value.operation_id)+'?subject=agent%2Fmissing');if(wrongSubject.status!==404)throw Error('Receipt read crossed subject scope');
 const replay=await request('/v1/client/actions',b.body);if(replay.status!==200||replay.value.status!=='applied')throw Error('Response-loss replay not frozen');
 const conflict=structuredClone(b.body);conflict.parameters.mutation.content='different';if((await request('/v1/client/actions',conflict)).status<400)throw Error('Digest conflict admitted');
 await poll(async()=>(await read()).native.idle,'native idle');delay=10000;native.stdin.write(JSON.stringify({type:'prompt',id:'busy-loss',message:'busy for process loss'})+'\n');native.stdin.flush();await poll(async()=>!(await read()).native.idle,'native process-loss busy');
 const lost=await action('lost',{type:'enqueue',content:'must not resend',lane:'steer'});if(lost.status!==200)throw Error(JSON.stringify(lost));const lostId=lost.value.harness_control.entry_id;
 await poll(async()=>(await read()).queue.entries.find(e=>e.id===lostId)?.status==='dispatched','owner dispatch reservation');native.kill('SIGKILL');await native.exited;await out;await err;
 const uncertain=await poll(async()=>{const r=await receipt(lost.value.operation_id);return r.status==='indeterminate'?r:false;},'native loss indeterminate');
 const frozen=await request('/v1/client/actions',lost.body);if(frozen.status!==200||frozen.value.status!=='indeterminate')throw Error('Lost response retry attempted resend');
 console.log('OWNER_CONTROL_SUCCESS '+JSON.stringify({owner_queue:'stable-id move/replace/cancel/promote',native_applied:applied,durable_queue:durable,durable_model:modelReceipt,uncertain,receipt_replay:'frozen',unauthorized:unauthorized.status,stale_turn:stale.status,stale_queue_revision:badRevision.status,approval:(await read()).native.approval}));console.log('OWNER_DRIVER_STDERR '+driverErrors);
} finally {clearTimeout(deadline);native?.kill();d.kill();await d.exited;console.log('OWNER_DAEMON_STDERR '+await daemonError);server.stop();await rm(root,{recursive:true,force:true});}
