//! Native subject contracts are derived from the gateway's effective registry/policy descriptors.
//! No native family, claim kind, field selection, or schema ID is maintained here.
use anyhow::{Context as _, Result, bail};
use serde_json::{Map, Value, json};
use std::collections::BTreeSet;
use std::fmt::Write as _;
use st3_schema::client_projection as policy;

pub struct Contract {
    native: policy::Contract,
}

impl std::ops::Deref for Contract {
    type Target = policy::Contract;
    fn deref(&self) -> &Self::Target { &self.native }
}

impl Contract {
    pub fn derive(base: &Value) -> Result<Self> {
        Ok(Self { native: policy::Contract::derive(base).map_err(anyhow::Error::msg)? })
    }

    pub fn apply(&self, schema: &mut Value) -> Result<()> {
        self.native.apply(schema).map_err(anyhow::Error::msg)
    }

    pub fn typescript(&self, schema: &Value) -> Result<String> {
        let mut out = String::from("// @generated by st3-client-codegen from native registry + client disclosure policy; do not edit.\n// Regenerate: cargo run -p st3-client-codegen; verify: cargo run -p st3-client-codegen -- --check\nimport type * as Models from './Models.generated.ts';\n");
        writeln!(out,"export const SUBJECT_FAMILY_SCHEMA_IDS = {} as const;",json!(self.families))?;
        writeln!(out,"export const SUBJECT_CLAIM_SCHEMA_IDS = {} as const;",json!(self.claims))?;
        writeln!(out,"export const SUBJECT_NATIVE_REGISTRY_DIGEST = {} as const;",self.discovery["native_registry_digest"])?;
        writeln!(out,"export const SUBJECT_PROJECTED_SCHEMA_SHA256 = {} as const;",self.discovery["projected_schema_sha256"])?;
        writeln!(out,"export const SUBJECT_PROJECTED_DIGEST_CONVENTION = {} as const;",self.discovery["projected_digest_convention"])?;
        writeln!(out,"const nativeReferenceContract = {} as const;",st3_schema::subject_reference_contract())?;
        writeln!(out,"const customEffective = {} as const;", self.custom_effective)?;
        let family_bindings = self.families.iter().map(|(name,id)| (id.clone(),self.definitions[name]["properties"]["family"]["const"].clone())).collect::<Map<_,_>>();
        let claim_bindings = self.claims.iter().map(|(name,id)| (id.clone(),json!({"family":self.definitions[name]["properties"]["ref"]["x-st-native-ref-families"][0],"kind":self.definitions[name]["properties"]["kind"]["const"]}))).collect::<Map<_,_>>();
        writeln!(out,"const familyBindings: Readonly<{{ [id: string]: string }}> = {};",Value::Object(family_bindings))?;
        writeln!(out,"const claimBindings: Readonly<{{ [id: string]: {{family: string; kind: string}} }}> = {};",Value::Object(claim_bindings))?;
        out.push_str(include_str!("../templates/Subjects.ts.in"));
        let defs = schema["$defs"].as_object().context("schema defs")?;
        let mut needed = BTreeSet::new();
        fn visit(name: &str, defs: &Map<String,Value>, needed: &mut BTreeSet<String>) -> Result<()> {
            if !needed.insert(name.to_owned()) { return Ok(()); }
            fn refs(value: &Value, found: &mut BTreeSet<String>) {
                match value {
                    Value::Object(map) => { if let Some(name) = map.get("$ref").and_then(Value::as_str).and_then(|name| name.strip_prefix("#/$defs/")) { found.insert(name.to_owned()); } for value in map.values() { refs(value,found); } },
                    Value::Array(values) => for value in values { refs(value,found); }, _ => {}
                }
            }
            let mut references = BTreeSet::new();
            refs(defs.get(name).with_context(|| format!("missing subject dependency {name}"))?,&mut references);
            for reference in references { visit(&reference,defs,needed)?; }
            Ok(())
        }
        for name in ["SubjectProjection","SubjectClaim","SubjectSchemas","SubjectsPage","SubjectClaimsPage","SubjectHistoryPage","SubjectCollectionFrame","Snapshot"] { visit(name,defs,&mut needed)?; }
        for name in needed {
            writeln!(out,"function is{name}(value: unknown): value is Models.{name} {{ return {}; }}",ts_guard(&defs[&name],"value")?)?;
        }
        Ok(out)
    }
}

fn ts_guard(schema: &Value, value: &str) -> Result<String> {
    if let Some(name) = schema["$ref"].as_str().and_then(|name|name.strip_prefix("#/$defs/")) { return Ok(format!("is{name}({value})")); }
    if let Some(literal) = schema.get("x-st-exact-json") {
        return Ok(format!("isExactJson({value}, {literal})"));
    }
    if let Some(families) = schema.get("x-st-native-ref-families") {
        return Ok(format!("isNativeSubjectReference({value}, {families})"));
    }
    if let Some(literal) = schema.get("const") { return Ok(format!("{value} === {literal}")); }
    if let Some(values) = schema["enum"].as_array() { return Ok(format!("({})",values.iter().map(|literal|format!("{value} === {literal}")).collect::<Vec<_>>().join(" || "))); }
    for key in ["oneOf","anyOf"] {
        if let Some(branches) = schema[key].as_array() { return Ok(format!("({})",branches.iter().map(|schema|ts_guard(schema,value)).collect::<Result<Vec<_>>>()?.join(" || "))); }
    }
    if let Some(types) = schema["type"].as_array() { return ts_guard(&json!({"anyOf":types.iter().map(|kind|json!({"type":kind})).collect::<Vec<_>>()}),value); }
    let mut checks = Vec::new();
    match schema["type"].as_str() {
        Some("null") => checks.push(format!("{value} === null")),
        Some("boolean" | "string") => checks.push(format!("typeof {value} === {}",schema["type"])),
        Some("integer") => checks.push(format!("typeof {value} === 'number' && Number.isSafeInteger({value})")),
        Some("number") => checks.push(format!("typeof {value} === 'number' && Number.isFinite({value})")),
        Some("array") => checks.push(format!("Array.isArray({value}) && {value}.every((item: unknown) => {})",ts_guard(&schema["items"],"item")?)),
        Some("object") => {
            checks.push(format!("isObject({value})"));
            let properties = schema["properties"].as_object();
            let required = schema["required"].as_array();
            if let Some(properties) = properties {
                for (name,field) in properties {
                    let key = json!(name);
                    let guard = ts_guard(field,&format!("{value}[{key}]"))?;
                    checks.push(if required.is_some_and(|items|items.iter().any(|item|item == name)) { format!("hasOwn({value}, {key}) && ({guard})") } else { format!("(!hasOwn({value}, {key}) || ({guard}))") });
                }
            }
            if schema["additionalProperties"] == false {
                let keys = json!(properties.map(|properties|properties.keys().collect::<Vec<_>>()).unwrap_or_default());
                checks.push(format!("Object.keys({value}).every(key => ({keys} as readonly string[]).includes(key))"));
            } else if schema["additionalProperties"].is_object() {
                checks.push(format!("Object.values({value}).every(item => {})",ts_guard(&schema["additionalProperties"],"item")?));
            }
        }
        None => checks.push("true".into()),
        Some(other) => bail!("unsupported native TS guard {other}"),
    }
    for (keyword,operator) in [("minimum",">="),("maximum","<="),("minLength",">="),("maxLength","<="),("minItems",">="),("maxItems","<=")] {
        if let Some(bound) = schema.get(keyword) {
            let member = if matches!(keyword,"minimum"|"maximum") { value.to_owned() } else { format!("{value}.length") };
            checks.push(format!("{member} {operator} {bound}"));
        }
    }
    if let Some(pattern) = schema.get("pattern") { checks.push(format!("new RegExp({pattern}, 'u').test({value})")); }
    if let Some(values) = schema["not"]["enum"].as_array() { checks.push(format!("![{}].includes({value})",values.iter().map(Value::to_string).collect::<Vec<_>>().join(","))); }
    Ok(format!("({})",checks.join(" && ")))
}

impl Contract {
    pub fn rich(&self) -> Result<String> {
        let mut out = String::new();
        writeln!(out,"\nexport const SUBJECT_NATIVE_REGISTRY_DIGEST = {} as const",json!(st3_schema::registry().digest()))?;
        writeln!(out,"export const SUBJECT_PROJECTED_SCHEMA_SHA256 = {} as const",self.artifact["projected_schema_sha256"])?;
        writeln!(out,"export const SUBJECT_FAMILY_CODECS = {{")?;
        for (name,id) in &self.families { writeln!(out,"{}: {name},",json!(id))?; }
        writeln!(out,"}} as const\nexport const SUBJECT_CLAIM_CODECS = {{")?;
        for (name,id) in &self.claims { writeln!(out,"{}: {name},",json!(id))?; }
        writeln!(out,"}} as const\nexport const SUBJECT_CUSTOM_CLAIM_CODEC = NativeCustomCustomClaim")?;
        out.push_str(include_str!("../templates/Subjects.effect.ts.in"));
        Ok(out)
    }
}
