import assert from 'node:assert/strict';
import { sidebarGroups, rememberResources } from './sidebarView.ts';
const register = value => ({ value, revision: 'claim/1' });
const folder = (name, key, parent = null) => ({ name: register(name), position: register({ key, parent }), tombstone: null });
const arrangement = { kind: 'arrangement', id: 'arrangement/person/avery/019a0000-0000-7000-8000-000000000001', owner: 'person/avery', deleted: false, body: { version: 1, name: register('Sidebar'), folders: { first: folder('First', 'a0'), second: folder('Second', 'a1') }, placements: { 'agent/a': register({ folder: 'first', key: 'a1' }), 'mission/b': register({ folder: 'first', key: 'a0' }) } } };
const current = [ { id: 'agent/a', title: 'Atlas', kind: 'Agents', target: 'agent/a' }, { id: 'mission/b', title: 'Build', kind: 'Missions', target: 'mission/b' }, { id: 'machine/demo', title: 'Demo', kind: 'Machines', target: 'machine/demo' } ];
const resources = rememberResources(new Map(), current);
const view = sidebarGroups([arrangement], resources);
assert.deepEqual(view.groups.map(group => group.title), ['First', 'Second', 'Machines']);
assert.deepEqual(view.groups[0].resources.map(row => row.id), ['mission/b', 'agent/a']);
assert.equal(view.groups[0].collapsed, false);
assert.equal(view.unfiledCount, 1);
const deletedFolder = structuredClone(arrangement);
deletedFolder.body.folders.first.tombstone = register(true);
assert.deepEqual(sidebarGroups([deletedFolder], resources).groups.map(group => group.title), ['Second', 'Agents', 'Missions', 'Machines']);
const resolved = structuredClone(arrangement);
resolved.resolved = { parents: {}, folders: { 'agent/a': null, 'mission/b': 'second' } };
assert.equal(sidebarGroups([resolved], resources).groups[1].resources[0].id, 'mission/b');
assert.equal(sidebarGroups([resolved], resources).groups.find(group => group.title === 'Agents').resources[0].id, 'agent/a');
const missing = rememberResources(resources, current.slice(1));
assert.equal(sidebarGroups([arrangement], missing).groups[0].resources[1].missing, true);
const unknown = structuredClone(arrangement);
unknown.body.placements['resource/example/absent'] = register({ folder: 'first', key: 'a2' });
assert.equal(sidebarGroups([unknown], resources).groups[0].resources.at(-1).missing, true);
const busy = rememberResources(new Map(), Array.from({ length: 31 }, (_, i) => ({ id: `agent/${i}`, kind: 'Agents', title: `Row ${i}`, target: `agent/${i}` })));
assert.equal(sidebarGroups([], busy).everythingCollapsed, true);
assert.equal(sidebarGroups([], busy, { everything: false }).everythingCollapsed, false);
assert.equal(sidebarGroups([], busy, {}, 'Row 30').everythingCollapsed, false);
assert.equal(sidebarGroups([], busy, {}, 'Row 30').groups[0].resources.length, 1);
assert.equal(sidebarGroups([arrangement], resources, { 'folder/first': true }).groups[0].collapsed, true);
// Viewing, searching and collapse choices never modify graph registers.
assert.equal(arrangement.body.placements['agent/a'].value.folder, 'first');
