// Frozen timeline declarations from Models.swift at 34c5cdcff (before blocks negotiation).
// Only the Timeline prefix is renamed; enum cases and decoding remain unchanged.
// Frozen pre-#1561 timeline decoder (34c5cdcff); names prefixed only to coexist.
import Foundation
import St3Client
public enum LegacyTimelineRole: String, Codable, Sendable { case system, user, assistant, tool }
public enum LegacyTimelineType: String, Codable, Sendable { case message, content, toolCall = "tool_call", toolResult = "tool_result", status, error, usage, redaction, truncation }
public enum LegacyTimelineToolStatus: String, Codable, Sendable { case success, error }
public enum LegacyTimelineStatus: String, Codable, Sendable { case queued, running, waiting, completed, failed, cancelled }
public enum LegacyTimelineUsageSemantics: String, Codable, Sendable { case contextOccupancy = "context_occupancy", sessionCumulative = "session_cumulative", response }
public struct LegacyTimelineMessageBody: Codable, Sendable { public let messageID: String; public let replyTo, from, to, title: String?; public let tags: [String]?; public let attachments: [Attachment]?; enum CodingKeys: String, CodingKey { case messageID = "message_id", replyTo = "reply_to", from, to, title, tags, attachments } }
public struct LegacyTimelineContentBody: Codable, Sendable { public let mediaType: String; public let text: String?; public let attachmentID: String?; enum CodingKeys: String, CodingKey { case mediaType = "media_type", text, attachmentID = "attachment_id" } }
public struct LegacyTimelineToolCallBody: Codable, Sendable { public let callID: String; public let name: String; public let arguments: JSONValue; enum CodingKeys: String, CodingKey { case callID = "call_id", name, arguments } }
public struct LegacyTimelineToolResultBody: Codable, Sendable { public let callID: String; public let status: LegacyTimelineToolStatus; public let mediaType: String; public let content: JSONValue; enum CodingKeys: String, CodingKey { case callID = "call_id", status, mediaType = "media_type", content } }
public struct LegacyTimelineStatusBody: Codable, Sendable { public let status: LegacyTimelineStatus; public let detail: String? }
public struct LegacyTimelineErrorBody: Codable, Sendable { public let code: String; public let message: String; public let retryable: Bool; public let details: [String: JSONValue] }
public struct LegacyTimelineAttribution: Codable, Sendable { public let agentID: String; public let missionRunID: String?; public let generationID: String?; public let stepID: String?; enum CodingKeys: String, CodingKey { case agentID = "agent_id", missionRunID = "mission_run_id", generationID = "generation_id", stepID = "step_id" } }
public struct LegacyTimelineUsageBody: Codable, Sendable { public let semantics: LegacyTimelineUsageSemantics; public let driver: String; public let model: String?; public let inputTokens: UInt64?; public let outputTokens: UInt64?; public let cachedTokens: UInt64?; public let totalTokens: UInt64?; public let contextUsedTokens: UInt64?; public let contextWindowTokens: UInt64?; public let contextUsedPercent: Double?; public let compactions: UInt64?; public let lastCompactionMs: UInt64?; public let lastCompactionTrigger: String?; public let cost: Double?; public let currency: String?; public let attribution: LegacyTimelineAttribution; enum CodingKeys: String, CodingKey { case semantics, driver, model, inputTokens = "input_tokens", outputTokens = "output_tokens", cachedTokens = "cached_tokens", totalTokens = "total_tokens", contextUsedTokens = "context_used_tokens", contextWindowTokens = "context_window_tokens", contextUsedPercent = "context_used_percent", compactions, lastCompactionMs = "last_compaction_ms", lastCompactionTrigger = "last_compaction_trigger", cost, currency, attribution } }
public struct LegacyTimelineRedactionBody: Codable, Sendable { public let reason: String; public let withheldBytes: UInt64; public let withheldItems: UInt64?; enum CodingKeys: String, CodingKey { case reason, withheldBytes = "withheld_bytes", withheldItems = "withheld_items" } }
public struct LegacyTimelineTruncationBody: Codable, Sendable { public let reason: String; public let omittedFromSequence: UInt64; public let omittedToSequence: UInt64; public let continuationCursor: String?; enum CodingKeys: String, CodingKey { case reason, omittedFromSequence = "omitted_from_sequence", omittedToSequence = "omitted_to_sequence", continuationCursor = "continuation_cursor" } }
public enum LegacyTimelineBody: Sendable { case message(LegacyTimelineMessageBody), content(LegacyTimelineContentBody), toolCall(LegacyTimelineToolCallBody), toolResult(LegacyTimelineToolResultBody), status(LegacyTimelineStatusBody), error(LegacyTimelineErrorBody), usage(LegacyTimelineUsageBody), redaction(LegacyTimelineRedactionBody), truncation(LegacyTimelineTruncationBody) }
public struct LegacyTimelineEntry: Codable, Sendable, Identifiable {
    public let id: String; public let sequence: UInt64; public let revision: UInt; public let timestamp: String; public let role: LegacyTimelineRole; public let type: LegacyTimelineType; public let isFinal: Bool; public let body: LegacyTimelineBody
    enum CodingKeys: String, CodingKey { case id, sequence, revision, timestamp, role, type, isFinal = "final", body }
    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: CodingKeys.self)
        id = try values.decode(String.self, forKey: .id); sequence = try values.decode(UInt64.self, forKey: .sequence); revision = try values.decode(UInt.self, forKey: .revision); timestamp = try values.decode(String.self, forKey: .timestamp); role = try values.decode(LegacyTimelineRole.self, forKey: .role); type = try values.decode(LegacyTimelineType.self, forKey: .type); isFinal = try values.decode(Bool.self, forKey: .isFinal)
        body = switch type { case .message: .message(try values.decode(LegacyTimelineMessageBody.self, forKey: .body)); case .content: .content(try values.decode(LegacyTimelineContentBody.self, forKey: .body)); case .toolCall: .toolCall(try values.decode(LegacyTimelineToolCallBody.self, forKey: .body)); case .toolResult: .toolResult(try values.decode(LegacyTimelineToolResultBody.self, forKey: .body)); case .status: .status(try values.decode(LegacyTimelineStatusBody.self, forKey: .body)); case .error: .error(try values.decode(LegacyTimelineErrorBody.self, forKey: .body)); case .usage: .usage(try values.decode(LegacyTimelineUsageBody.self, forKey: .body)); case .redaction: .redaction(try values.decode(LegacyTimelineRedactionBody.self, forKey: .body)); case .truncation: .truncation(try values.decode(LegacyTimelineTruncationBody.self, forKey: .body)) }
    }
    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: CodingKeys.self); try values.encode(id, forKey: .id); try values.encode(sequence, forKey: .sequence); try values.encode(revision, forKey: .revision); try values.encode(timestamp, forKey: .timestamp); try values.encode(role, forKey: .role); try values.encode(type, forKey: .type); try values.encode(isFinal, forKey: .isFinal)
        switch body { case .message(let value): try values.encode(value, forKey: .body); case .content(let value): try values.encode(value, forKey: .body); case .toolCall(let value): try values.encode(value, forKey: .body); case .toolResult(let value): try values.encode(value, forKey: .body); case .status(let value): try values.encode(value, forKey: .body); case .error(let value): try values.encode(value, forKey: .body); case .usage(let value): try values.encode(value, forKey: .body); case .redaction(let value): try values.encode(value, forKey: .body); case .truncation(let value): try values.encode(value, forKey: .body) }
    }
}
