import * as stylex from '@stylexjs/stylex'
import { tokens } from './tokens.stylex.ts'
import { colorVars as c } from '../../../../packages/fractal-ui/src/assistant-ui/composition-tokens.stylex.ts'
export const liveLegacyTheme = stylex.createTheme(tokens, {
'--ds-amber-100': c.message,
'--ds-amber-200': c.message,
'--ds-amber-300': c.message,
'--ds-amber-600': c.attention,
'--ds-amber-700': c.attention,
'--ds-amber-900': c.attention,
'--ds-background-100': c.canvas,
'--ds-background-200': c.raised,
'--ds-blue-100': c.message,
'--ds-blue-1000': c.primary,
'--ds-blue-200': c.message,
'--ds-blue-300': c.message,
'--ds-blue-600': c.primary,
'--ds-blue-700': c.primary,
'--ds-blue-900': c.primary,
'--ds-focus-color': c.primary,
'--ds-focus-ring': `0 0 0 2px ${c.primary}`,
'--ds-foreground': c.fg,
'--ds-gray-1000': c.fg,
'--ds-gray-200': c.message,
'--ds-gray-400': c.borderStrong,
'--ds-gray-500': c.borderStrong,
'--ds-gray-600': c.borderStrong,
'--ds-gray-700': c.fgMuted,
'--ds-gray-800': c.fgMuted,
'--ds-gray-900': c.fg,
'--ds-gray-alpha-100': c.message,
'--ds-gray-alpha-200': c.message,
'--ds-gray-alpha-300': c.message,
'--ds-gray-alpha-400': c.borderStrong,
'--ds-gray-alpha-500': c.borderStrong,
'--ds-gray-alpha-600': c.borderStrong,
'--ds-green-100': c.message,
'--ds-green-300': c.message,
'--ds-green-700': c.done,
'--ds-green-900': c.done,
'--ds-purple-100': c.message,
'--ds-purple-300': c.message,
'--ds-purple-700': c.primary,
'--ds-purple-900': c.primary,
'--ds-red-100': c.message,
'--ds-red-300': c.message,
'--ds-red-400': c.message,
'--ds-red-700': c.dangerFg,
'--ds-red-900': c.dangerFg,
'--ds-shadow-medium': '0 8px 24px rgb(0 0 0 / 0.18)',
})
