/** Original compatibility semantics mapped to Fractal's independently authored palette. */
import * as stylex from '@stylexjs/stylex'
export const tokens = stylex.defineVars({
'--ds-amber-100': 'color-mix(in srgb, var(--warning) 15%, var(--panel))',
'--ds-amber-200': 'color-mix(in srgb, var(--warning) 15%, var(--panel))',
'--ds-amber-300': 'color-mix(in srgb, var(--warning) 15%, var(--panel))',
'--ds-amber-600': 'var(--warning)',
'--ds-amber-700': 'var(--warning)',
'--ds-amber-900': 'var(--warning)',
'--ds-background-100': 'var(--canvas)',
'--ds-background-200': 'var(--panel)',
'--ds-blue-100': 'color-mix(in srgb, var(--accent) 15%, var(--panel))',
'--ds-blue-1000': 'var(--accent)',
'--ds-blue-200': 'color-mix(in srgb, var(--accent) 15%, var(--panel))',
'--ds-blue-300': 'color-mix(in srgb, var(--accent) 15%, var(--panel))',
'--ds-blue-600': 'var(--accent)',
'--ds-blue-700': 'var(--accent)',
'--ds-blue-900': 'var(--accent)',
'--ds-focus-color': 'var(--accent)',
'--ds-focus-ring': '0 0 0 2px var(--accent)',
'--ds-foreground': 'var(--ink)',
'--ds-gray-1000': 'var(--ink)',
'--ds-gray-200': 'var(--recess)',
'--ds-gray-400': 'var(--line)',
'--ds-gray-500': 'var(--line)',
'--ds-gray-600': 'var(--line)',
'--ds-gray-700': 'var(--muted)',
'--ds-gray-800': 'var(--muted)',
'--ds-gray-900': 'var(--ink)',
'--ds-gray-alpha-100': 'var(--recess)',
'--ds-gray-alpha-200': 'var(--recess)',
'--ds-gray-alpha-300': 'var(--recess)',
'--ds-gray-alpha-400': 'var(--line)',
'--ds-gray-alpha-500': 'var(--line)',
'--ds-gray-alpha-600': 'var(--line)',
'--ds-green-100': 'color-mix(in srgb, var(--good) 15%, var(--panel))',
'--ds-green-300': 'color-mix(in srgb, var(--good) 15%, var(--panel))',
'--ds-green-700': 'var(--good)',
'--ds-green-900': 'var(--good)',
'--ds-purple-100': 'color-mix(in srgb, var(--accent) 15%, var(--panel))',
'--ds-purple-300': 'color-mix(in srgb, var(--accent) 15%, var(--panel))',
'--ds-purple-700': 'var(--accent)',
'--ds-purple-900': 'var(--accent)',
'--ds-red-100': 'color-mix(in srgb, var(--danger) 15%, var(--panel))',
'--ds-red-300': 'color-mix(in srgb, var(--danger) 15%, var(--panel))',
'--ds-red-400': 'color-mix(in srgb, var(--danger) 15%, var(--panel))',
'--ds-red-700': 'var(--danger)',
'--ds-red-900': 'var(--danger)',
'--ds-shadow-medium': '0 8px 24px rgb(0 0 0 / 0.18)',
})

export const scale = Object.assign((units: number): string => String(units * 4) + 'px', {
fontSans: 'var(--sans, Arial, sans-serif)',
fontMono: 'var(--mono, ui-monospace, monospace)',
radiusDefault: 'var(--radius, 4px)', radiusSm: '2px', radiusLg: 'var(--panel-radius, 8px)', radiusFull: '9999px',
space1: '4px',
space2: '8px',
space3: '12px',
space4: '16px',
space5: '20px',
space6: '24px',
space8: '32px',
space10: '40px',
space12: '48px',
})
