// tests/unit/launch.test.ts — brief-016 `smalltalk launch` core.
//
// Focus: identity resolution, command-argv construction, pty.toml
// content, dry-run flow. Actual harness spawning is out of scope for
// unit tests — we exercise the captureOnly/dryRun seams that return
// the constructed argv without executing anything.

import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import type { CliContext } from '../../src/cli-context.ts';
import { cmdLaunch } from '../../src/commands/launch.ts';

let scratch: string;
let cwd: string;
let coordRoot: string;
let home: string;
let stderrBuf: string;
let stdoutBuf: string;
let ctx: CliContext;

beforeEach(() => {
  scratch = mkdtempSync(join(tmpdir(), 'st-launch-'));
  cwd = join(scratch, 'repo');
  coordRoot = join(scratch, 'state');
  home = join(scratch, 'home');
  mkdirSync(cwd, { recursive: true });
  mkdirSync(coordRoot, { recursive: true });
  mkdirSync(home, { recursive: true });
  stderrBuf = '';
  stdoutBuf = '';
  ctx = {
    env: {},
    coordRoot,
    coordConfig: '/unused',
    stdout: (s) => {
      stdoutBuf += s;
    },
    stderr: (s) => {
      stderrBuf += s;
    },
    readStdin: async () => Buffer.alloc(0),
  };
});

afterEach(() => {
  rmSync(scratch, { recursive: true, force: true });
});

function baseInput(overrides: Partial<Parameters<typeof cmdLaunch>[0]> = {}) {
  return {
    harness: 'claude' as const,
    cwd,
    home,
    coordRoot,
    env: {} as NodeJS.ProcessEnv,
    dryRun: true,
    ptyBinPath: '', // treat as pty NOT on PATH
    ...overrides,
  };
}

// ─── Identity resolution ───────────────────────────────────────────────

describe('cmdLaunch — identity resolution', () => {
  it('uses --identity when set', async () => {
    const r = await cmdLaunch(baseInput({ identity: 'alice' }), ctx);
    expect(r.identity).toBe('alice');
    expect(r.identityAutoGenerated).toBe(false);
    expect(stderrBuf).not.toMatch(/anon-/);
  });

  it('falls back to $ST_AGENT when --identity is unset', async () => {
    const r = await cmdLaunch(
      baseInput({ env: { ST_AGENT: 'bob' } }),
      ctx
    );
    expect(r.identity).toBe('bob');
    expect(r.identityAutoGenerated).toBe(false);
  });

  it('falls back to $ST_IDENTITY when ST_AGENT unset (deprecation chain)', async () => {
    const r = await cmdLaunch(
      baseInput({ env: { ST_IDENTITY: 'legacy-alice' } }),
      ctx
    );
    expect(r.identity).toBe('legacy-alice');
    expect(r.identityAutoGenerated).toBe(false);
  });

  it('falls back to $COORD_IDENTITY when neither ST_* is set', async () => {
    const r = await cmdLaunch(
      baseInput({ env: { COORD_IDENTITY: 'legacy-coord-bob' } }),
      ctx
    );
    expect(r.identity).toBe('legacy-coord-bob');
    expect(r.identityAutoGenerated).toBe(false);
  });

  it('generates anon-<rand6> when no identity is available', async () => {
    const r = await cmdLaunch(baseInput({}), ctx);
    expect(r.identity).toMatch(/^anon-[0-9a-z]{6}$/);
    expect(r.identityAutoGenerated).toBe(true);
    expect(stderrBuf).toMatch(/no ST_AGENT set/);
    expect(stderrBuf).toMatch(/set ST_AGENT to persist/);
    expect(stderrBuf).toMatch(/anon-[0-9a-z]{6}/);
  });

  it('explicit --identity wins over $ST_AGENT', async () => {
    const r = await cmdLaunch(
      baseInput({ identity: 'explicit', env: { ST_AGENT: 'from-env' } }),
      ctx
    );
    expect(r.identity).toBe('explicit');
  });
});

// ─── Channel-mode defaults ─────────────────────────────────────────────

describe('cmdLaunch — channel mode defaults', () => {
  it('claude defaults to channel-mode on', async () => {
    const r = await cmdLaunch(baseInput({ harness: 'claude' }), ctx);
    expect(r.channel).toBe(true);
    expect(r.argv.join(' ')).toContain(
      '--dangerously-load-development-channels server:st'
    );
  });

  it('codex defaults to channel-mode off', async () => {
    const r = await cmdLaunch(baseInput({ harness: 'codex' }), ctx);
    expect(r.channel).toBe(false);
  });

  it('--no-channel disables channel on claude', async () => {
    const r = await cmdLaunch(
      baseInput({ harness: 'claude', noChannel: true }),
      ctx
    );
    expect(r.channel).toBe(false);
    expect(r.argv.join(' ')).not.toContain(
      '--dangerously-load-development-channels'
    );
  });
});

// ─── Command argv construction ─────────────────────────────────────────

describe('cmdLaunch — command argv', () => {
  it('claude direct path uses --resume with a session id', async () => {
    const r = await cmdLaunch(
      baseInput({ harness: 'claude', identity: 'alice' }),
      ctx
    );
    expect(r.argv[0]).toBe('claude');
    expect(r.argv).toContain('--resume');
    expect(r.argv).toContain('--permission-mode');
    expect(r.argv).toContain('auto');
  });

  it('codex direct path uses `codex resume <sid>` when .codex-session-id exists', async () => {
    writeFileSync(join(cwd, '.codex-session-id'), 'abc-123\n');
    const r = await cmdLaunch(baseInput({ harness: 'codex' }), ctx);
    expect(r.argv).toEqual(['codex', 'resume', 'abc-123']);
  });

  it('codex direct path is bare `codex` when no .codex-session-id', async () => {
    const r = await cmdLaunch(baseInput({ harness: 'codex' }), ctx);
    expect(r.argv).toEqual(['codex']);
  });

  it('--model routes through `ollama launch <harness> --model <spec>`', async () => {
    const r = await cmdLaunch(
      baseInput({ harness: 'claude', model: 'glm-5.2:cloud' }),
      ctx
    );
    expect(r.argv).toEqual([
      'ollama',
      'launch',
      'claude',
      '--model',
      'glm-5.2:cloud',
    ]);
    expect(r.usedOllama).toBe(true);
  });

  it('--model works for codex too', async () => {
    const r = await cmdLaunch(
      baseInput({ harness: 'codex', model: 'glm-5.2:cloud' }),
      ctx
    );
    expect(r.argv).toEqual([
      'ollama',
      'launch',
      'codex',
      '--model',
      'glm-5.2:cloud',
    ]);
    expect(r.usedOllama).toBe(true);
  });
});

// ─── brief-023: --permission-mode ─────────────────────────────────────

describe('cmdLaunch — --permission-mode (brief-023)', () => {
  // Sanity anchor: no flag, no env → auto in BOTH bootstrap and main
  // argv. Guards against a future refactor that changes the default
  // silently, which would demote eval-spinner posture back to `auto`
  // for callers that had been relying on the flag override.
  it('defaults to auto when neither flag nor env is set', async () => {
    const r = await cmdLaunch(
      baseInput({ harness: 'claude', identity: 'alice' }),
      ctx
    );
    expect(r.permissionMode).toBe('auto');
    // Main argv has exactly one --permission-mode + auto pair.
    const idx = r.argv.indexOf('--permission-mode');
    expect(idx).toBeGreaterThanOrEqual(0);
    expect(r.argv[idx + 1]).toBe('auto');
  });

  it('explicit --permission-mode overrides everything', async () => {
    const r = await cmdLaunch(
      baseInput({
        harness: 'claude',
        identity: 'alice',
        permissionMode: 'bypassPermissions',
        env: { CLAUDE_PERMISSION_MODE: 'plan' },
      }),
      ctx
    );
    expect(r.permissionMode).toBe('bypassPermissions');
    const idx = r.argv.indexOf('--permission-mode');
    expect(r.argv[idx + 1]).toBe('bypassPermissions');
  });

  it('CLAUDE_PERMISSION_MODE env kicks in when the flag is absent', async () => {
    const r = await cmdLaunch(
      baseInput({
        harness: 'claude',
        identity: 'alice',
        env: { CLAUDE_PERMISSION_MODE: 'bypassPermissions' },
      }),
      ctx
    );
    expect(r.permissionMode).toBe('bypassPermissions');
    const idx = r.argv.indexOf('--permission-mode');
    expect(r.argv[idx + 1]).toBe('bypassPermissions');
  });

  it('empty --permission-mode value falls through to env, then default', async () => {
    // Guard against argv shape `--permission-mode ""` (an operator
    // wired it through a variable that expanded to empty). We treat
    // empty like "unset" so the env / default tier still resolves,
    // rather than passing "" to claude which would reject it.
    const r = await cmdLaunch(
      baseInput({
        harness: 'claude',
        identity: 'alice',
        permissionMode: '',
        env: {},
      }),
      ctx
    );
    expect(r.permissionMode).toBe('auto');
  });

  it('mode is baked into the generated pty.toml command line', async () => {
    const r = await cmdLaunch(
      baseInput({
        harness: 'claude',
        identity: 'alice',
        permissionMode: 'bypassPermissions',
      }),
      ctx
    );
    // pty.toml quotes the shell line; we don't reconstruct it here,
    // just assert the resolved mode appears in the emitted preview.
    expect(r.ptyTomlPreview).toContain('--permission-mode bypassPermissions');
    expect(r.ptyTomlPreview).not.toContain('--permission-mode auto');
  });

  it('codex launches accept the flag silently (surface has no effect)', async () => {
    // The mode resolves in `LaunchResult` regardless of harness so the
    // dry-run summary is consistent, but the codex argv is untouched.
    const r = await cmdLaunch(
      baseInput({
        harness: 'codex',
        identity: 'alice',
        permissionMode: 'bypassPermissions',
      }),
      ctx
    );
    expect(r.permissionMode).toBe('bypassPermissions');
    expect(r.argv).not.toContain('--permission-mode');
  });

  it('CLI wrapper: --permission-mode flag appears in the dry-run summary', async () => {
    const { cmdLaunchCli } = await import('../../src/commands/launch.ts');
    const rc = await cmdLaunchCli(
      [
        'claude',
        '--identity',
        'alice',
        '--permission-mode',
        'bypassPermissions',
        '--dry-run',
      ],
      ctx
    );
    expect(rc).toBe(0);
    expect(stdoutBuf).toContain('permission-mode: bypassPermissions');
    // And still shows up in the harness argv line.
    expect(stdoutBuf).toContain('--permission-mode bypassPermissions');
  });

  it('CLI wrapper: default summary shows permission-mode: auto', async () => {
    const { cmdLaunchCli } = await import('../../src/commands/launch.ts');
    await cmdLaunchCli(['claude', '--identity', 'alice', '--dry-run'], ctx);
    expect(stdoutBuf).toContain('permission-mode: auto');
  });
});

// ─── --agent alias (Johannes's cl1/cl2) ─────────────────────────────────

describe('cmdLaunch — --agent / $AGENT (aliased claude binaries)', () => {
  it('defaults to `claude` when neither flag nor env is set', async () => {
    const r = await cmdLaunch(
      baseInput({ harness: 'claude', identity: 'alice' }),
      ctx
    );
    expect(r.agentBinary).toBe('claude');
    expect(r.argv[0]).toBe('claude');
  });

  it('explicit --agent overrides everything (flag > env > default)', async () => {
    const r = await cmdLaunch(
      baseInput({
        harness: 'claude',
        identity: 'alice',
        agentBinary: 'cl1',
        env: { AGENT: 'cl2' },
      }),
      ctx
    );
    expect(r.agentBinary).toBe('cl1');
    expect(r.argv[0]).toBe('cl1');
  });

  it('$AGENT env kicks in when the flag is absent', async () => {
    const r = await cmdLaunch(
      baseInput({
        harness: 'claude',
        identity: 'alice',
        env: { AGENT: 'cl2' },
      }),
      ctx
    );
    expect(r.agentBinary).toBe('cl2');
    expect(r.argv[0]).toBe('cl2');
  });

  it('empty --agent value falls through to env, then default', async () => {
    // Guard against argv shape `--agent ""` (an operator wired it
    // through a variable that expanded to empty). Empty is treated
    // like "unset" so the env / default tier still resolves,
    // matching how --permission-mode handles the same shape.
    const r1 = await cmdLaunch(
      baseInput({
        harness: 'claude',
        identity: 'alice',
        agentBinary: '',
        env: { AGENT: 'cl2' },
      }),
      ctx
    );
    expect(r1.agentBinary).toBe('cl2');

    const r2 = await cmdLaunch(
      baseInput({
        harness: 'claude',
        identity: 'alice',
        agentBinary: '',
        env: {},
      }),
      ctx
    );
    expect(r2.agentBinary).toBe('claude');
  });

  it('alias is baked into the generated pty.toml command line', async () => {
    const r = await cmdLaunch(
      baseInput({
        harness: 'claude',
        identity: 'alice',
        agentBinary: 'cl1',
      }),
      ctx
    );
    // pty.toml's `command = "..."` value shell-joins the argv; the
    // alias appears as the first token after `command = "`. Assert
    // the emitted preview starts the command line with cl1 and does
    // NOT invoke the default `claude` binary (would drift the pty
    // session away from the aliased build the operator wanted).
    expect(r.ptyTomlPreview).toMatch(/command = "cl1 /);
    expect(r.ptyTomlPreview).not.toMatch(/command = "claude /);
  });

  it('codex launches ignore --agent (codex has its own launcher)', async () => {
    // Per the brief, `--agent` only affects the claude binary. Codex
    // launches surface the resolution in the dry-run so the operator
    // can eyeball what's happening, but the codex argv is untouched.
    const r = await cmdLaunch(
      baseInput({
        harness: 'codex',
        identity: 'alice',
        agentBinary: 'cl1',
      }),
      ctx
    );
    expect(r.agentBinary).toBe('cl1');
    expect(r.argv).not.toContain('cl1');
    expect(r.argv[0]).toBe('codex');
  });

  it('bootstrap argv also uses the alias (jsonl init handoff)', async () => {
    // The bootstrap `claude --print --session-id …` runs before the
    // main `--resume`. If it uses the default `claude` while main uses
    // the alias, the bootstrap picks the wrong binary and the jsonl
    // is written into the wrong session — a subtle correctness bug.
    // We route argv[0] resolution through the same `agentBinary`
    // input so bootstrap + main line up.
    const r = await cmdLaunch(
      baseInput({
        harness: 'claude',
        identity: 'alice',
        agentBinary: 'cl1',
      }),
      ctx
    );
    // captureOnly / dry-run bakes the alias into the returned argv;
    // the bootstrap argv isn't exposed on LaunchResult, but the
    // pty.toml preview reflects the invocation the pty layer will
    // spawn, which is the same array `buildClaudeCommand` returns
    // as `mainArgv`. If argv[0] is aliased, the bootstrap (derived
    // from the same call) is aliased too. Sanity: assert exactly one
    // `cl1` token in the argv[0] position.
    expect(r.argv[0]).toBe('cl1');
    expect(r.argv.filter((a) => a === 'cl1')).toHaveLength(1);
  });

  it('CLI wrapper: --agent flag appears in the dry-run summary', async () => {
    const { cmdLaunchCli } = await import('../../src/commands/launch.ts');
    const rc = await cmdLaunchCli(
      ['claude', '--identity', 'alice', '--agent', 'cl1', '--dry-run'],
      ctx
    );
    expect(rc).toBe(0);
    expect(stdoutBuf).toContain('agent binary:   cl1');
    // And in the harness argv line.
    expect(stdoutBuf).toMatch(/harness argv:\n\s*cl1\s/);
  });

  it('CLI wrapper: default summary shows `agent binary: claude`', async () => {
    const { cmdLaunchCli } = await import('../../src/commands/launch.ts');
    await cmdLaunchCli(['claude', '--identity', 'alice', '--dry-run'], ctx);
    expect(stdoutBuf).toContain('agent binary:   claude');
  });

  it('CLI wrapper: $AGENT env populates the summary when no --agent flag', async () => {
    const { cmdLaunchCli } = await import('../../src/commands/launch.ts');
    // Route AGENT through the ctx env, matching how a real shell
    // would set it before the CLI reads process.env.
    ctx.env = { AGENT: 'cl2' } as NodeJS.ProcessEnv;
    await cmdLaunchCli(['claude', '--identity', 'alice', '--dry-run'], ctx);
    expect(stdoutBuf).toContain('agent binary:   cl2');
  });
});

// ─── pty.toml content ─────────────────────────────────────────────────

describe('cmdLaunch — pty.toml generation', () => {
  it('emits a pty.toml preview even when pty is not on PATH', async () => {
    const r = await cmdLaunch(baseInput({ identity: 'alice' }), ctx);
    expect(r.ptyTomlPreview).not.toBeNull();
    // Prefix comes from identity (F3): unique per agent by
    // construction, so pty's global namespace can't collide when two
    // clones of the same repo launch under different identities.
    expect(r.ptyTomlPreview).toContain('prefix = "alice"');
    expect(r.ptyTomlPreview).toContain('[sessions.claude]');
    expect(r.ptyTomlPreview).toContain('ST_AGENT = "alice"');
  });

  it('prefix reflects the identity even when identity differs from cwd basename', async () => {
    // The point of F3 — a taskflow-dev identity launched from a
    // taskflow/ cwd should have a `taskflow-dev`-prefixed pty session
    // so a generic shepherd (or `pty send`) targeting the identity
    // hits it. Historic behavior was `prefix = "taskflow"` which lost
    // the identity in the pty namespace.
    const r = await cmdLaunch(
      baseInput({ identity: 'taskflow-dev' }),
      ctx
    );
    expect(r.ptyTomlPreview).toContain('prefix = "taskflow-dev"');
  });

  it('claude preview has no ding sidecar', async () => {
    const r = await cmdLaunch(
      baseInput({ harness: 'claude', identity: 'alice' }),
      ctx
    );
    expect(r.ptyTomlPreview).not.toContain('[sessions.ding]');
  });

  it('codex preview includes the coord ding sidecar', async () => {
    const r = await cmdLaunch(
      baseInput({ harness: 'codex', identity: 'alice' }),
      ctx
    );
    expect(r.ptyTomlPreview).toContain('[sessions.ding]');
    expect(r.ptyTomlPreview).toContain(
      'coord ding codex --identity alice'
    );
    expect(r.ptyTomlPreview).toContain('strategy = "permanent"');
  });

  it('--session-name overrides the pty session key', async () => {
    const r = await cmdLaunch(
      baseInput({ harness: 'codex', identity: 'alice', sessionName: 'agentx' }),
      ctx
    );
    expect(r.ptyTomlPreview).toContain('[sessions.agentx]');
    expect(r.ptyTomlPreview).toContain(
      'coord ding agentx --identity alice'
    );
  });
});

// ─── F1: --unattended auto-poker ──────────────────────────────────────

describe('cmdLaunch — --unattended auto-poker (F1)', () => {
  // The poker prepends a background subshell that pty-sends 4 Enter
  // keys with 4s spacing before exec'ing the main claude command,
  // so Claude Code's first-launch TUI gates (workspace trust,
  // dev-channels warning, resume-mode dialog) all get an Enter each
  // hands-off. See notes/agent-onboarding.md:126-133 for the dialogs
  // this closes.

  it('default (no flag, no stdinIsTty) → poker NOT baked', async () => {
    const r = await cmdLaunch(
      baseInput({ harness: 'claude', identity: 'alice' }),
      ctx
    );
    expect(r.unattended).toBe(false);
    expect(r.ptyTomlPreview).not.toContain('pty send');
    expect(r.ptyTomlPreview).not.toContain('sleep 4');
  });

  it('unattended: true → poker baked, targets `<identity>-<sessionName>` (dash, not slash)', async () => {
    // pty's ptyfile.ts:58 joins prefix + sessionName with a DASH
    // (`${prefix}-${rawName}`), not a slash. The slash-form target
    // (`alice/claude`) was the P5 re-run's true-0-poke blocker: every
    // `pty send` returned "Session not found" and the CoS-spawned
    // worker deadlocked at the dev-channels gate. See PR fixing
    // this and cos's ptr into ../pty/src/ptyfile.ts:58.
    const r = await cmdLaunch(
      baseInput({ harness: 'claude', identity: 'alice', unattended: true }),
      ctx
    );
    expect(r.unattended).toBe(true);
    // 4 pokes with 4s spacing each, targeting the DASH-joined name.
    expect(r.ptyTomlPreview).toContain(
      'sleep 4 && pty send alice-claude --seq key:return'
    );
    // Sanity: the slash form must NOT appear — that was the bug.
    expect(r.ptyTomlPreview).not.toContain('pty send alice/claude');
    // Backgrounded subshell + `exec` for the main command.
    expect(r.ptyTomlPreview).toMatch(/\)\s*&\s*exec/);
  });

  it('poker respects a custom --session-name (still dash-joined)', async () => {
    const r = await cmdLaunch(
      baseInput({
        harness: 'claude',
        identity: 'taskflow-dev',
        sessionName: 'primary',
        unattended: true,
      }),
      ctx
    );
    expect(r.ptyTomlPreview).toContain(
      'pty send taskflow-dev-primary --seq key:return'
    );
    expect(r.ptyTomlPreview).not.toContain('taskflow-dev/primary');
  });

  it('auto-on when stdinIsTty() reports false', async () => {
    const stdinTtyCtx: CliContext = {
      ...ctx,
      stdinIsTty: () => false,
    };
    const r = await cmdLaunch(
      baseInput({ harness: 'claude', identity: 'alice' }),
      stdinTtyCtx
    );
    expect(r.unattended).toBe(true);
    expect(r.ptyTomlPreview).toContain('pty send alice-claude');
  });

  it('stays attended when stdinIsTty() reports true', async () => {
    const stdinTtyCtx: CliContext = {
      ...ctx,
      stdinIsTty: () => true,
    };
    const r = await cmdLaunch(
      baseInput({ harness: 'claude', identity: 'alice' }),
      stdinTtyCtx
    );
    expect(r.unattended).toBe(false);
    expect(r.ptyTomlPreview).not.toContain('pty send');
  });

  it('explicit unattended: false overrides auto-on-no-TTY (--attended escape hatch)', async () => {
    const stdinTtyCtx: CliContext = {
      ...ctx,
      stdinIsTty: () => false,
    };
    const r = await cmdLaunch(
      baseInput({
        harness: 'claude',
        identity: 'alice',
        unattended: false,
      }),
      stdinTtyCtx
    );
    expect(r.unattended).toBe(false);
    expect(r.ptyTomlPreview).not.toContain('pty send');
  });

  it('codex harness is NEVER poked, even with unattended: true', async () => {
    // Codex has no dev-channels flag and its resume-mode UX is
    // different. The poker is Claude-Code-specific.
    const r = await cmdLaunch(
      baseInput({ harness: 'codex', identity: 'alice', unattended: true }),
      ctx
    );
    // LaunchResult still reflects the caller's intent for observability.
    expect(r.unattended).toBe(true);
    // But the pty.toml command line is untouched.
    expect(r.ptyTomlPreview).not.toContain('pty send');
    expect(r.ptyTomlPreview).not.toContain('sleep 4');
  });

  it('CLI --unattended flag threads through', async () => {
    const { cmdLaunchCli } = await import('../../src/commands/launch.ts');
    await cmdLaunchCli(
      ['claude', '--identity', 'alice', '--unattended', '--dry-run'],
      ctx
    );
    expect(stdoutBuf).toContain('unattended:     yes');
  });

  it('CLI --attended overrides an auto-on-no-TTY resolution', async () => {
    const stdinTtyCtx: CliContext = {
      ...ctx,
      stdinIsTty: () => false,
    };
    const { cmdLaunchCli } = await import('../../src/commands/launch.ts');
    await cmdLaunchCli(
      ['claude', '--identity', 'alice', '--attended', '--dry-run'],
      stdinTtyCtx
    );
    expect(stdoutBuf).toContain('unattended:     no');
  });
});

// ─── pty detection + write behavior ────────────────────────────────────

describe('cmdLaunch — pty detection', () => {
  it('reports pty unavailable when detection returns empty', async () => {
    const r = await cmdLaunch(baseInput({ ptyBinPath: '' }), ctx);
    expect(r.usedPty).toBe(false);
    expect(r.ptyTomlPath).toBeNull();
  });

  it('reports pty available when ptyBinPath is a real file', async () => {
    const fakePty = join(scratch, 'fake-pty');
    writeFileSync(fakePty, '#!/bin/sh\necho ok\n');
    const r = await cmdLaunch(baseInput({ ptyBinPath: fakePty }), ctx);
    expect(r.usedPty).toBe(true);
    expect(r.ptyTomlPath).toBe(join(cwd, 'pty.toml'));
  });

  it('--no-pty forces off even when pty is available', async () => {
    const fakePty = join(scratch, 'fake-pty');
    writeFileSync(fakePty, '#!/bin/sh\necho ok\n');
    const r = await cmdLaunch(
      baseInput({ ptyBinPath: fakePty, noPty: true }),
      ctx
    );
    expect(r.usedPty).toBe(false);
  });
});

// ─── .claude-session-id handling ───────────────────────────────────────

describe('cmdLaunch — claude session id', () => {
  it('reads an existing .claude-session-id and preserves it', async () => {
    writeFileSync(
      join(cwd, '.claude-session-id'),
      'preserved-uuid-1234\n'
    );
    const r = await cmdLaunch(
      baseInput({ harness: 'claude', identity: 'alice' }),
      ctx
    );
    expect(r.argv).toContain('preserved-uuid-1234');
    expect(r.claudeSessionIdPath).toBe(join(cwd, '.claude-session-id'));
    // dry-run didn't overwrite.
    expect(readFileSync(join(cwd, '.claude-session-id'), 'utf8')).toBe(
      'preserved-uuid-1234\n'
    );
  });

  it('codex path has no .claude-session-id reference', async () => {
    const r = await cmdLaunch(baseInput({ harness: 'codex' }), ctx);
    expect(r.claudeSessionIdPath).toBeNull();
  });
});

// ─── Dry-run stdout summary ────────────────────────────────────────────

describe('cmdLaunchCli — dry-run summary', () => {
  it('the CLI wrapper prints the summary block on --dry-run', async () => {
    // Route through the CLI wrapper for the assertions on stdout.
    const { cmdLaunchCli } = await import('../../src/commands/launch.ts');
    const rc = await cmdLaunchCli(
      ['claude', '--identity', 'alice', '--dry-run'],
      ctx
    );
    expect(rc).toBe(0);
    expect(stdoutBuf).toContain('identity:       alice');
    expect(stdoutBuf).toContain('channel mode:   on');
    expect(stdoutBuf).toContain('harness argv:');
    expect(stdoutBuf).toContain('pty.toml');
  });

  it('the CLI wrapper reports an anon fallback line in the summary', async () => {
    const { cmdLaunchCli } = await import('../../src/commands/launch.ts');
    await cmdLaunchCli(['codex', '--dry-run'], ctx);
    expect(stdoutBuf).toMatch(/identity:.+anon-[0-9a-z]{6}/);
    expect(stdoutBuf).toContain('throwaway; set ST_AGENT to persist');
  });

  it('errors on an unsupported harness', async () => {
    const { cmdLaunchCli } = await import('../../src/commands/launch.ts');
    await expect(
      cmdLaunchCli(['pi'], ctx)
    ).rejects.toThrow(/unknown harness/);
  });

  it('errors on an unknown flag', async () => {
    const { cmdLaunchCli } = await import('../../src/commands/launch.ts');
    await expect(
      cmdLaunchCli(['claude', '--bogus'], ctx)
    ).rejects.toThrow(/unknown flag/);
  });

  it('missing harness arg → help + exit 2', async () => {
    const { cmdLaunchCli } = await import('../../src/commands/launch.ts');
    const rc = await cmdLaunchCli([], ctx);
    expect(rc).toBe(2);
    expect(stderrBuf).toContain('usage: st launch');
  });

  it('--help returns 0 and prints the help block', async () => {
    const { cmdLaunchCli } = await import('../../src/commands/launch.ts');
    const rc = await cmdLaunchCli(['--help'], ctx);
    expect(rc).toBe(0);
    expect(stderrBuf).toContain('usage: st launch');
    expect(stderrBuf).toContain('--model');
    expect(stderrBuf).toContain('anon-<rand6>');
  });
});

// ─── Ensures inbox/archive created for the resolved identity ───────────

describe('cmdLaunch — side effects (non-dry-run)', () => {
  it('lazy-creates the agent inbox+archive when not dry-run', async () => {
    // Non-dry-run path; ptyBinPath='' so no pty spawn happens, and
    // captureOnly true to skip the actual harness spawn.
    await cmdLaunch(
      baseInput({
        identity: 'carol',
        dryRun: false,
        captureOnly: true,
      }),
      ctx
    );
    expect(existsSync(join(coordRoot, 'carol', 'inbox'))).toBe(true);
    expect(existsSync(join(coordRoot, 'carol', 'archive'))).toBe(true);
  });

  it('writes pty.toml (skip-if-exists) when pty is available', async () => {
    const fakePty = join(scratch, 'fake-pty');
    writeFileSync(fakePty, '#!/bin/sh\necho ok\n');
    await cmdLaunch(
      baseInput({
        identity: 'dave',
        ptyBinPath: fakePty,
        dryRun: false,
        captureOnly: true,
      }),
      ctx
    );
    const path = join(cwd, 'pty.toml');
    expect(existsSync(path)).toBe(true);
    const content = readFileSync(path, 'utf8');
    expect(content).toContain('ST_AGENT = "dave"');

    // Second run does NOT overwrite (skip-if-exists).
    writeFileSync(path, '# user hand-edited\n');
    await cmdLaunch(
      baseInput({
        identity: 'eve',
        ptyBinPath: fakePty,
        dryRun: false,
        captureOnly: true,
      }),
      ctx
    );
    expect(readFileSync(path, 'utf8')).toBe('# user hand-edited\n');
  });

  it('writes a fresh .claude-session-id when none exists (claude path)', async () => {
    await cmdLaunch(
      baseInput({
        harness: 'claude',
        identity: 'frank',
        dryRun: false,
        captureOnly: true,
      }),
      ctx
    );
    const path = join(cwd, '.claude-session-id');
    expect(existsSync(path)).toBe(true);
    // UUID shape: 8-4-4-4-12 hex.
    const content = readFileSync(path, 'utf8').trim();
    expect(content).toMatch(
      /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/
    );
  });
});

// ─── Live-path regression (brief-016 followup: require-not-defined) ────
//
// These tests exercise the code paths that a `--dry-run` skips —
// specifically the newUuid()/randomUUID call site that crashed under
// CJS `require('node:crypto')` when smalltalk ran as ESM. A `require`
// regression here fails the test rather than the live user run.

describe('cmdLaunch — live-path regression (dry-run bypasses this)', () => {
  it('claude live path: .claude-session-id + mcp.json + pty.toml all land on disk without runtime errors', async () => {
    // captureOnly: true skips only the harness spawn; every earlier
    // side-effect (session-id gen via randomUUID, cmdInit write,
    // pty.toml write, ensureIdentityDirs) runs for real.
    const fakePty = join(scratch, 'fake-pty');
    writeFileSync(fakePty, '#!/bin/sh\necho ok\n');
    let threw: unknown = null;
    try {
      await cmdLaunch(
        baseInput({
          harness: 'claude',
          identity: 'live-alice',
          dryRun: false,
          captureOnly: true,
          ptyBinPath: fakePty,
        }),
        ctx
      );
    } catch (err) {
      threw = err;
    }
    expect(threw).toBeNull();
    // The three files that must exist post-live-run:
    expect(existsSync(join(cwd, '.claude-session-id'))).toBe(true);
    expect(existsSync(join(cwd, '.mcp.json'))).toBe(true);
    expect(existsSync(join(cwd, 'pty.toml'))).toBe(true);
    // And the UUID must be well-formed — proves randomUUID() was
    // actually reachable at runtime (a `require`-not-defined regression
    // throws before this write happens).
    const sid = readFileSync(
      join(cwd, '.claude-session-id'),
      'utf8'
    ).trim();
    expect(sid).toMatch(
      /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/
    );
  });

  it('codex live path: mcp.json + pty.toml with ding sidecar land without runtime errors', async () => {
    const fakePty = join(scratch, 'fake-pty');
    writeFileSync(fakePty, '#!/bin/sh\necho ok\n');
    let threw: unknown = null;
    try {
      await cmdLaunch(
        baseInput({
          harness: 'codex',
          identity: 'live-bob',
          dryRun: false,
          captureOnly: true,
          ptyBinPath: fakePty,
        }),
        ctx
      );
    } catch (err) {
      threw = err;
    }
    expect(threw).toBeNull();
    expect(existsSync(join(cwd, '.mcp.json'))).toBe(true);
    const pty = readFileSync(join(cwd, 'pty.toml'), 'utf8');
    expect(pty).toContain('[sessions.codex]');
    expect(pty).toContain('[sessions.ding]');
    expect(pty).toContain('coord ding codex --identity live-bob');
    // Codex path doesn't touch newUuid(), but the init.ts /
    // status.ts sibling `require`s in the error paths are compiled
    // in this run — a regression there would still surface.
  });

  it('two live launches in a row generate distinct UUIDs (proves randomUUID is not memoized)', async () => {
    const cwd2 = join(scratch, 'repo2');
    mkdirSync(cwd2, { recursive: true });
    await cmdLaunch(
      baseInput({
        harness: 'claude',
        identity: 'live-carol',
        dryRun: false,
        captureOnly: true,
      }),
      ctx
    );
    await cmdLaunch(
      baseInput({
        harness: 'claude',
        identity: 'live-dave',
        cwd: cwd2,
        dryRun: false,
        captureOnly: true,
      }),
      ctx
    );
    const sid1 = readFileSync(
      join(cwd, '.claude-session-id'),
      'utf8'
    ).trim();
    const sid2 = readFileSync(
      join(cwd2, '.claude-session-id'),
      'utf8'
    ).trim();
    expect(sid1).not.toBe(sid2);
  });
});

// ─── brief-118: settings.local.json with asyncRewake SessionStart ──────

describe('cmdLaunch — .claude/settings.local.json generation (brief-118)', () => {
  function fakeHooksDir(): string {
    // A directory containing fake hook scripts. Content is irrelevant —
    // the launch only records absolute paths in the generated JSON;
    // Claude Code executes the scripts, not the launcher.
    const dir = join(scratch, 'fake-hooks');
    mkdirSync(dir, { recursive: true });
    for (const name of ['session-start.sh', 'pre-compact.sh', 'stop-failure.sh']) {
      writeFileSync(join(dir, name), '#!/bin/sh\nexit 0\n');
    }
    return dir;
  }

  it('dry-run preview contains all three hooks pointing at absolute paths', async () => {
    const hooksDir = fakeHooksDir();
    // Opt out of the ST_BIN injection so the command:s are bare script
    // paths and stable across dev machines. The ST_BIN=… wiring has
    // its own tests below.
    const r = await cmdLaunch(
      baseInput({ identity: 'alice', hooksDir, stBinForHooks: null }),
      ctx
    );
    expect(r.claudeSettingsPath).toBe(join(cwd, '.claude', 'settings.local.json'));
    expect(r.claudeSettingsPreview).not.toBeNull();
    const preview = r.claudeSettingsPreview!;
    // The asyncRewake attribute IS the load-bearing bit for #118.
    expect(preview).toContain('"async": true');
    expect(preview).toContain('"asyncRewake": true');
    expect(preview).toContain(`"command": "${join(hooksDir, 'session-start.sh')}"`);
    expect(preview).toContain(`"command": "${join(hooksDir, 'pre-compact.sh')}"`);
    expect(preview).toContain(`"command": "${join(hooksDir, 'stop-failure.sh')}"`);
    // Absolute paths only — Claude Code doesn't resolve ~ or relative.
    expect(preview).toMatch(/"command":\s*"\/.+session-start\.sh"/);
    // JSON must parse — a tool that generates unparseable JSON would
    // silently break every downstream Claude Code run.
    expect(() => JSON.parse(preview)).not.toThrow();
  });

  it('F2: enableAllProjectMcpServers + enabledMcpjsonServers pre-approve the st MCP', async () => {
    // Without these, first-boot claude prompts "Enable the st
    // MCP server?" — a hands-off standup can't answer that. Docs-
    // confirmed fields; see code.claude.com/docs/en/settings.
    const hooksDir = fakeHooksDir();
    const r = await cmdLaunch(
      baseInput({ identity: 'alice', hooksDir, stBinForHooks: null }),
      ctx
    );
    const parsed = JSON.parse(r.claudeSettingsPreview!);
    expect(parsed.enableAllProjectMcpServers).toBe(true);
    // Pin the specific server name — `st` matches the post-cutover
    // key that `st init` now writes into `.mcp.json` (see
    // src/commands/init.ts). A future `.mcp.json` edit that adds an
    // unrelated server still requires an explicit approval —
    // belt-and-braces alongside the blanket allow.
    expect(parsed.enabledMcpjsonServers).toEqual(['st']);
  });

  it('asyncRewake is ONLY on the SessionStart hook (not PreCompact or StopFailure)', async () => {
    const hooksDir = fakeHooksDir();
    const r = await cmdLaunch(baseInput({ identity: 'alice', hooksDir }), ctx);
    const parsed = JSON.parse(r.claudeSettingsPreview!);
    const ss = parsed.hooks.SessionStart[0].hooks[0];
    const pc = parsed.hooks.PreCompact[0].hooks[0];
    const sf = parsed.hooks.StopFailure[0].hooks[0];
    expect(ss.async).toBe(true);
    expect(ss.asyncRewake).toBe(true);
    expect(pc.async).toBeUndefined();
    expect(pc.asyncRewake).toBeUndefined();
    expect(sf.async).toBeUndefined();
    expect(sf.asyncRewake).toBeUndefined();
  });

  it('writes .claude/settings.local.json on live run when absent', async () => {
    const hooksDir = fakeHooksDir();
    await cmdLaunch(
      baseInput({
        identity: 'george',
        hooksDir,
        stBinForHooks: null,
        dryRun: false,
        captureOnly: true,
      }),
      ctx
    );
    const path = join(cwd, '.claude', 'settings.local.json');
    expect(existsSync(path)).toBe(true);
    const parsed = JSON.parse(readFileSync(path, 'utf8'));
    expect(parsed.hooks.SessionStart[0].hooks[0].asyncRewake).toBe(true);
    expect(parsed.hooks.SessionStart[0].hooks[0].command).toBe(
      join(hooksDir, 'session-start.sh')
    );
  });

  it('skip-if-exists: does not overwrite an existing settings.local.json', async () => {
    const hooksDir = fakeHooksDir();
    const settingsDir = join(cwd, '.claude');
    const settingsFile = join(settingsDir, 'settings.local.json');
    mkdirSync(settingsDir, { recursive: true });
    writeFileSync(settingsFile, '{"_user_hand_edited": true}\n');
    await cmdLaunch(
      baseInput({
        identity: 'hanna',
        hooksDir,
        dryRun: false,
        captureOnly: true,
      }),
      ctx
    );
    expect(readFileSync(settingsFile, 'utf8')).toBe(
      '{"_user_hand_edited": true}\n'
    );
  });

  it('--no-hooks / noHooks: true skips generation entirely', async () => {
    const hooksDir = fakeHooksDir();
    const r = await cmdLaunch(
      baseInput({ identity: 'ivan', hooksDir, noHooks: true }),
      ctx
    );
    expect(r.claudeSettingsPath).toBeNull();
    expect(r.claudeSettingsPreview).toBeNull();
    // Confirm live-run also skips.
    await cmdLaunch(
      baseInput({
        identity: 'ivan-live',
        hooksDir,
        noHooks: true,
        dryRun: false,
        captureOnly: true,
      }),
      ctx
    );
    expect(existsSync(join(cwd, '.claude', 'settings.local.json'))).toBe(false);
  });

  it('codex harness skips settings.local.json (no Claude Code hooks)', async () => {
    const hooksDir = fakeHooksDir();
    const r = await cmdLaunch(
      baseInput({ harness: 'codex', identity: 'juno', hooksDir }),
      ctx
    );
    expect(r.claudeSettingsPath).toBeNull();
    expect(r.claudeSettingsPreview).toBeNull();
  });

  it('missing hooks dir: soft-skip with a stderr notice, launch still succeeds', async () => {
    const missing = join(scratch, 'no-such-dir');
    const r = await cmdLaunch(
      baseInput({ identity: 'kai', hooksDir: missing }),
      ctx
    );
    expect(r.claudeSettingsPath).toBeNull();
    expect(r.claudeSettingsPreview).toBeNull();
    expect(stderrBuf).toContain('shipped Claude Code hooks not found on disk');
  });

  // ─── ST_BIN injection into hook command:s ────────────────────────────
  //
  // The hook scripts shellout to `st`/`coord`. On a degenerate PATH (or
  // a stale `coord` that shadows the launched version), that lookup
  // silently uses the wrong binary. `st launch` fixes this by baking
  // an absolute `ST_BIN=<abs>` assignment into each hook's `command:`
  // string — Claude Code runs shell-form commands via `sh -c`, so the
  // POSIX assignment-preceded simple command form applies.

  it('ST_BIN=<abs> is prepended to every hook command when stBinForHooks is a string', async () => {
    const hooksDir = fakeHooksDir();
    const fakeStBin = '/opt/smalltalk/bin/st';
    const r = await cmdLaunch(
      baseInput({
        identity: 'moss',
        hooksDir,
        stBinForHooks: fakeStBin,
      }),
      ctx
    );
    const parsed = JSON.parse(r.claudeSettingsPreview!);
    for (const stage of ['SessionStart', 'PreCompact', 'StopFailure'] as const) {
      const cmd = parsed.hooks[stage][0].hooks[0].command;
      expect(cmd).toContain(`ST_BIN=${fakeStBin} `);
      expect(cmd.endsWith('.sh')).toBe(true);
    }
  });

  it('ST_BIN=<abs> uses shell-safe single-quoting when the path has spaces', async () => {
    const hooksDir = fakeHooksDir();
    const fakeStBin = "/opt/weird path/'quotes'/bin/st";
    const r = await cmdLaunch(
      baseInput({
        identity: 'nell',
        hooksDir,
        stBinForHooks: fakeStBin,
      }),
      ctx
    );
    const parsed = JSON.parse(r.claudeSettingsPreview!);
    const cmd = parsed.hooks.SessionStart[0].hooks[0].command;
    // Path with spaces + embedded single quotes must be quoted per
    // shellQuote — the value is wrapped in single quotes and each
    // internal single quote is escaped as `'\''`.
    expect(cmd).toContain("ST_BIN='/opt/weird path/'\\''quotes'\\''/bin/st'");
  });

  it('stBinForHooks: null opts out — commands are bare script paths', async () => {
    const hooksDir = fakeHooksDir();
    const r = await cmdLaunch(
      baseInput({
        identity: 'oleg',
        hooksDir,
        stBinForHooks: null,
      }),
      ctx
    );
    const parsed = JSON.parse(r.claudeSettingsPreview!);
    for (const stage of ['SessionStart', 'PreCompact', 'StopFailure'] as const) {
      const cmd = parsed.hooks[stage][0].hooks[0].command;
      expect(cmd).not.toContain('ST_BIN=');
    }
  });

  it('stBinForHooks default (undefined) auto-resolves via resolveStBinPath', async () => {
    // Under the real test runner, the smalltalk repo IS an
    // `@myobie/coord`-named package with a valid `bin/st` on disk. The
    // auto-resolution should therefore succeed and inject an absolute
    // path that ends in `/bin/st`.
    const hooksDir = fakeHooksDir();
    const r = await cmdLaunch(
      baseInput({ identity: 'petra', hooksDir }),
      ctx
    );
    const parsed = JSON.parse(r.claudeSettingsPreview!);
    const cmd = parsed.hooks.SessionStart[0].hooks[0].command;
    expect(cmd).toMatch(/^ST_BIN=\/.+\/bin\/st\s/);
  });

  it('CLI --no-hooks flag threads through to noHooks: true', async () => {
    const hooksDir = fakeHooksDir();
    // Route through the CLI wrapper; can't pass hooksDir there, so
    // we rely on --no-hooks to skip generation regardless.
    void hooksDir;
    const { cmdLaunchCli } = await import('../../src/commands/launch.ts');
    await cmdLaunchCli(
      ['claude', '--identity', 'lena', '--no-hooks', '--dry-run'],
      ctx
    );
    expect(stdoutBuf).not.toContain('claude hooks:');
    expect(stdoutBuf).not.toContain('settings.local.json');
  });

  it('dry-run summary surfaces the settings.local.json path + JSON preview', async () => {
    const hooksDir = fakeHooksDir();
    // Route through cmdLaunch directly (the CLI wrapper doesn't accept
    // hooksDir), then verify the preview is well-formed.
    const r = await cmdLaunch(baseInput({ identity: 'mira', hooksDir }), ctx);
    expect(r.claudeSettingsPath).toBe(join(cwd, '.claude', 'settings.local.json'));
    expect(r.claudeSettingsPreview).toMatch(/"asyncRewake":\s*true/);
  });
});

// ─── brief-118: help text + hook-file-list stability ───────────────────

describe('cmdLaunch — --no-hooks help text', () => {
  it('--help mentions the --no-hooks flag', async () => {
    const { cmdLaunchCli } = await import('../../src/commands/launch.ts');
    await cmdLaunchCli(['--help'], ctx);
    expect(stderrBuf).toContain('--no-hooks');
    expect(stderrBuf).toContain('asyncRewake');
  });
});

// ─── brief-022: --persona persona install ───────────────────────────────

describe('cmdLaunch — --persona (brief-022)', () => {
  function makeGitRepo(dir: string): void {
    // Enough to satisfy readGitExclude — just the .git dir and info/.
    // We don't need an actual git binary; the launch code only reads
    // .git/info/exclude and appends to it.
    mkdirSync(join(dir, '.git', 'info'), { recursive: true });
  }

  function personaFixture(text = '# Persona\n\nHello.\n'): string {
    const path = join(scratch, 'persona.md');
    writeFileSync(path, text);
    return path;
  }

  it('returns persona=null when --persona is not passed', async () => {
    makeGitRepo(cwd);
    const r = await cmdLaunch(baseInput({ identity: 'a' }), ctx);
    expect(r.persona).toBeNull();
  });

  it('claude: copies persona to PERSONA.md and creates CLAUDE.md with @PERSONA.md when missing', async () => {
    makeGitRepo(cwd);
    const src = personaFixture('# You are the test agent\n');
    const r = await cmdLaunch(
      baseInput({
        harness: 'claude',
        identity: 'a',
        persona: src,
        dryRun: false,
        captureOnly: true,
      }),
      ctx
    );
    expect(r.persona).not.toBeNull();
    expect(r.persona!.entryFile).toBe('CLAUDE.md');
    expect(r.persona!.entryFileCreated).toBe(true);
    expect(r.persona!.importLineAppended).toBe(true);

    const copied = readFileSync(join(cwd, 'PERSONA.md'), 'utf8');
    expect(copied).toBe('# You are the test agent\n');

    const entry = readFileSync(join(cwd, 'CLAUDE.md'), 'utf8');
    expect(entry).toBe('@PERSONA.md\n');
  });

  it('codex: same shape but writes AGENTS.md', async () => {
    makeGitRepo(cwd);
    const src = personaFixture();
    const r = await cmdLaunch(
      baseInput({
        harness: 'codex',
        identity: 'a',
        persona: src,
        dryRun: false,
        captureOnly: true,
      }),
      ctx
    );
    expect(r.persona!.entryFile).toBe('AGENTS.md');
    expect(existsSync(join(cwd, 'AGENTS.md'))).toBe(true);
    expect(existsSync(join(cwd, 'CLAUDE.md'))).toBe(false);
    const entry = readFileSync(join(cwd, 'AGENTS.md'), 'utf8');
    expect(entry).toBe('@PERSONA.md\n');
  });

  it('preserves an existing CLAUDE.md: appends @PERSONA.md without clobbering', async () => {
    makeGitRepo(cwd);
    const existing =
      '# Project notes\n\nWe use TypeScript strict mode everywhere.\n';
    writeFileSync(join(cwd, 'CLAUDE.md'), existing);
    const src = personaFixture();
    const r = await cmdLaunch(
      baseInput({
        harness: 'claude',
        identity: 'a',
        persona: src,
        dryRun: false,
        captureOnly: true,
      }),
      ctx
    );
    expect(r.persona!.entryFileCreated).toBe(false);
    expect(r.persona!.importLineAppended).toBe(true);
    const entry = readFileSync(join(cwd, 'CLAUDE.md'), 'utf8');
    // Existing content intact, import appended after.
    expect(entry.startsWith(existing)).toBe(true);
    expect(entry).toContain('@PERSONA.md');
    // The import line must be on its own line (matching the pattern
    // we detect for idempotence).
    expect(/^@PERSONA\.md$/m.test(entry)).toBe(true);
  });

  it('idempotent: does not re-append @PERSONA.md when already present', async () => {
    makeGitRepo(cwd);
    const existing =
      '# Project\n\n@PERSONA.md\n\nMore project content.\n';
    writeFileSync(join(cwd, 'CLAUDE.md'), existing);
    const src = personaFixture();
    const r = await cmdLaunch(
      baseInput({
        harness: 'claude',
        identity: 'a',
        persona: src,
        dryRun: false,
        captureOnly: true,
      }),
      ctx
    );
    expect(r.persona!.entryFileCreated).toBe(false);
    expect(r.persona!.importLineAppended).toBe(false);
    // Content must be byte-identical.
    expect(readFileSync(join(cwd, 'CLAUDE.md'), 'utf8')).toBe(existing);
  });

  it('handles an existing CLAUDE.md that does not end in a newline', async () => {
    makeGitRepo(cwd);
    const existing = '# Project (no trailing newline)';
    writeFileSync(join(cwd, 'CLAUDE.md'), existing);
    const src = personaFixture();
    await cmdLaunch(
      baseInput({
        harness: 'claude',
        identity: 'a',
        persona: src,
        dryRun: false,
        captureOnly: true,
      }),
      ctx
    );
    const entry = readFileSync(join(cwd, 'CLAUDE.md'), 'utf8');
    // Original bytes preserved, separator + import added.
    expect(entry).toBe('# Project (no trailing newline)\n@PERSONA.md\n');
  });

  it('git-exclude: adds PERSONA.md + .mcp.json + .claude-session-id + .codex-session-id + pty.toml + entryFile (when we created it)', async () => {
    makeGitRepo(cwd);
    const src = personaFixture();
    const r = await cmdLaunch(
      baseInput({
        harness: 'claude',
        identity: 'a',
        persona: src,
        dryRun: false,
        captureOnly: true,
      }),
      ctx
    );
    const excludeText = readFileSync(
      join(cwd, '.git', 'info', 'exclude'),
      'utf8'
    );
    expect(excludeText).toContain('PERSONA.md');
    expect(excludeText).toContain('.mcp.json');
    expect(excludeText).toContain('.claude-session-id');
    expect(excludeText).toContain('.codex-session-id');
    expect(excludeText).toContain('pty.toml');
    expect(excludeText).toContain('CLAUDE.md');
    expect(r.persona!.gitExcludeEntriesAdded).toContain('CLAUDE.md');
  });

  it('git-exclude: does NOT add CLAUDE.md when it pre-existed', async () => {
    makeGitRepo(cwd);
    writeFileSync(join(cwd, 'CLAUDE.md'), '# Real repo CLAUDE.md\n');
    const src = personaFixture();
    const r = await cmdLaunch(
      baseInput({
        harness: 'claude',
        identity: 'a',
        persona: src,
        dryRun: false,
        captureOnly: true,
      }),
      ctx
    );
    const excludeText = readFileSync(
      join(cwd, '.git', 'info', 'exclude'),
      'utf8'
    );
    expect(excludeText).toContain('PERSONA.md');
    expect(excludeText).not.toContain('\nCLAUDE.md\n');
    expect(r.persona!.gitExcludeEntriesAdded).not.toContain('CLAUDE.md');
    // Entry file itself is untouched (except the appended import).
    const entry = readFileSync(join(cwd, 'CLAUDE.md'), 'utf8');
    expect(entry.startsWith('# Real repo CLAUDE.md\n')).toBe(true);
  });

  it('git-exclude: dedupes against existing entries', async () => {
    makeGitRepo(cwd);
    // Pre-seed the exclude file with a few of the expected entries.
    const preExisting = '# user notes\n.mcp.json\nPERSONA.md\n';
    writeFileSync(
      join(cwd, '.git', 'info', 'exclude'),
      preExisting
    );
    const src = personaFixture();
    const r = await cmdLaunch(
      baseInput({
        harness: 'claude',
        identity: 'a',
        persona: src,
        dryRun: false,
        captureOnly: true,
      }),
      ctx
    );
    expect(r.persona!.gitExcludeEntriesAdded).not.toContain('PERSONA.md');
    expect(r.persona!.gitExcludeEntriesAdded).not.toContain('.mcp.json');
    // But the others were still added.
    expect(r.persona!.gitExcludeEntriesAdded).toContain('pty.toml');
    const excludeText = readFileSync(
      join(cwd, '.git', 'info', 'exclude'),
      'utf8'
    );
    // Original content preserved.
    expect(excludeText.startsWith(preExisting)).toBe(true);
  });

  it('non-git cwd: warns and still installs persona files', async () => {
    // No .git dir.
    const src = personaFixture();
    const r = await cmdLaunch(
      baseInput({
        harness: 'claude',
        identity: 'a',
        persona: src,
        dryRun: false,
        captureOnly: true,
      }),
      ctx
    );
    expect(r.persona!.gitRepoAbsent).toBe(true);
    expect(r.persona!.gitExcludeEntriesAdded).toHaveLength(0);
    // Files still installed.
    expect(existsSync(join(cwd, 'PERSONA.md'))).toBe(true);
    expect(existsSync(join(cwd, 'CLAUDE.md'))).toBe(true);
    // Warning surfaced on stderr.
    expect(stderrBuf).toMatch(/not a git repo/);
  });

  it('missing --persona source: throws helpful error naming the flag + path', async () => {
    makeGitRepo(cwd);
    const bad = join(scratch, 'does-not-exist.md');
    await expect(
      cmdLaunch(
        baseInput({
          harness: 'claude',
          identity: 'a',
          persona: bad,
          dryRun: false,
          captureOnly: true,
        }),
        ctx
      )
    ).rejects.toThrow(/--persona.*could not read persona file/);
  });

  it('dry-run: reports the plan but touches nothing on disk', async () => {
    makeGitRepo(cwd);
    const src = personaFixture();
    const r = await cmdLaunch(
      baseInput({
        harness: 'claude',
        identity: 'a',
        persona: src,
        dryRun: true,
      }),
      ctx
    );
    expect(r.persona).not.toBeNull();
    expect(r.persona!.importLineAppended).toBe(true);
    expect(r.persona!.entryFileCreated).toBe(true);
    expect(r.persona!.gitExcludeEntriesAdded.length).toBeGreaterThan(0);
    // Nothing on disk.
    expect(existsSync(join(cwd, 'PERSONA.md'))).toBe(false);
    expect(existsSync(join(cwd, 'CLAUDE.md'))).toBe(false);
    expect(existsSync(join(cwd, '.git', 'info', 'exclude'))).toBe(false);
  });
});
